//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProduction) DeepCopyInto(out *BitcoinBlockProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProduction.
func (in *BitcoinBlockProduction) DeepCopy() *BitcoinBlockProduction {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionList) DeepCopyInto(out *BitcoinBlockProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionList.
func (in *BitcoinBlockProductionList) DeepCopy() *BitcoinBlockProductionList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionSpec) DeepCopyInto(out *BitcoinBlockProductionSpec) {
	*out = *in
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionSpec.
func (in *BitcoinBlockProductionSpec) DeepCopy() *BitcoinBlockProductionSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionStatus) DeepCopyInto(out *BitcoinBlockProductionStatus) {
	*out = *in
	if in.LastCompletedAt != nil {
		in, out := &in.LastCompletedAt, &out.LastCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionStatus.
func (in *BitcoinBlockProductionStatus) DeepCopy() *BitcoinBlockProductionStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductionPolicy) DeepCopyInto(out *ProductionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductionPolicy.
func (in *ProductionPolicy) DeepCopy() *ProductionPolicy {
	if in == nil {
		return nil
	}
	out := new(ProductionPolicy)
	in.DeepCopyInto(out)
	return out
}
