//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	actionsv1alpha1 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/actions/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionReservation) DeepCopyInto(out *ActionReservation) {
	*out = *in
	in.AdmittedAt.DeepCopyInto(&out.AdmittedAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	out.Network = in.Network
	out.Target = in.Target
	out.Policy = in.Policy
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastCompletedAt != nil {
		in, out := &in.LastCompletedAt, &out.LastCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionReservation.
func (in *ActionReservation) DeepCopy() *ActionReservation {
	if in == nil {
		return nil
	}
	out := new(ActionReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProduction) DeepCopyInto(out *BitcoinBlockProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProduction.
func (in *BitcoinBlockProduction) DeepCopy() *BitcoinBlockProduction {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionList) DeepCopyInto(out *BitcoinBlockProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionList.
func (in *BitcoinBlockProductionList) DeepCopy() *BitcoinBlockProductionList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionSpec) DeepCopyInto(out *BitcoinBlockProductionSpec) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionSpec.
func (in *BitcoinBlockProductionSpec) DeepCopy() *BitcoinBlockProductionSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionStatus) DeepCopyInto(out *BitcoinBlockProductionStatus) {
	*out = *in
	if in.NextOpportunityAt != nil {
		in, out := &in.NextOpportunityAt, &out.NextOpportunityAt
		*out = (*in).DeepCopy()
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetLedger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionStatus.
func (in *BitcoinBlockProductionStatus) DeepCopy() *BitcoinBlockProductionStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinProductionTarget) DeepCopyInto(out *BitcoinProductionTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinProductionTarget.
func (in *BitcoinProductionTarget) DeepCopy() *BitcoinProductionTarget {
	if in == nil {
		return nil
	}
	out := new(BitcoinProductionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinProductionTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinProductionTargetList) DeepCopyInto(out *BitcoinProductionTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinProductionTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinProductionTargetList.
func (in *BitcoinProductionTargetList) DeepCopy() *BitcoinProductionTargetList {
	if in == nil {
		return nil
	}
	out := new(BitcoinProductionTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinProductionTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinProductionTargetSpec) DeepCopyInto(out *BitcoinProductionTargetSpec) {
	*out = *in
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinProductionTargetSpec.
func (in *BitcoinProductionTargetSpec) DeepCopy() *BitcoinProductionTargetSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinProductionTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinProductionTargetStatus) DeepCopyInto(out *BitcoinProductionTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reorganization != nil {
		in, out := &in.Reorganization, &out.Reorganization
		*out = new(ReorganizationReservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(GenerationReservation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastCompletedAt != nil {
		in, out := &in.LastCompletedAt, &out.LastCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinProductionTargetStatus.
func (in *BitcoinProductionTargetStatus) DeepCopy() *BitcoinProductionTargetStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinProductionTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerationReservation) DeepCopyInto(out *GenerationReservation) {
	*out = *in
	in.ActionReservation.DeepCopyInto(&out.ActionReservation)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.NextDispatchAt != nil {
		in, out := &in.NextDispatchAt, &out.NextDispatchAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerationReservation.
func (in *GenerationReservation) DeepCopy() *GenerationReservation {
	if in == nil {
		return nil
	}
	out := new(GenerationReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductionOpportunity) DeepCopyInto(out *ProductionOpportunity) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductionOpportunity.
func (in *ProductionOpportunity) DeepCopy() *ProductionOpportunity {
	if in == nil {
		return nil
	}
	out := new(ProductionOpportunity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductionPolicy) DeepCopyInto(out *ProductionPolicy) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(RegtestInitialization)
		**out = **in
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]ProductionTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductionPolicy.
func (in *ProductionPolicy) DeepCopy() *ProductionPolicy {
	if in == nil {
		return nil
	}
	out := new(ProductionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductionTarget) DeepCopyInto(out *ProductionTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductionTarget.
func (in *ProductionTarget) DeepCopy() *ProductionTarget {
	if in == nil {
		return nil
	}
	out := new(ProductionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegtestInitialization) DeepCopyInto(out *RegtestInitialization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegtestInitialization.
func (in *RegtestInitialization) DeepCopy() *RegtestInitialization {
	if in == nil {
		return nil
	}
	out := new(RegtestInitialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReorganizationReservation) DeepCopyInto(out *ReorganizationReservation) {
	*out = *in
	in.ActionReservation.DeepCopyInto(&out.ActionReservation)
	out.Spec = in.Spec
	out.OriginalChain = in.OriginalChain
	out.ForkParent = in.ForkParent
	if in.ReplacementBlockHashes != nil {
		in, out := &in.ReplacementBlockHashes, &out.ReplacementBlockHashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VerifiedTip != nil {
		in, out := &in.VerifiedTip, &out.VerifiedTip
		*out = new(actionsv1alpha1.BitcoinChainPoint)
		**out = **in
	}
	if in.FinalChain != nil {
		in, out := &in.FinalChain, &out.FinalChain
		*out = new(actionsv1alpha1.BitcoinChainPoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReorganizationReservation.
func (in *ReorganizationReservation) DeepCopy() *ReorganizationReservation {
	if in == nil {
		return nil
	}
	out := new(ReorganizationReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetLedger) DeepCopyInto(out *TargetLedger) {
	*out = *in
	if in.Opportunity != nil {
		in, out := &in.Opportunity, &out.Opportunity
		*out = new(ProductionOpportunity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetLedger.
func (in *TargetLedger) DeepCopy() *TargetLedger {
	if in == nil {
		return nil
	}
	out := new(TargetLedger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPolicy) DeepCopyInto(out *TargetPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPolicy.
func (in *TargetPolicy) DeepCopy() *TargetPolicy {
	if in == nil {
		return nil
	}
	out := new(TargetPolicy)
	in.DeepCopyInto(out)
	return out
}
