
{{- if .Values.bitcoinGeneration.enabled }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "stacks-action-operator.fullname" . }}-generation
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    count/bitcoinblockgenerations.actions.stacks.org: "64"
{{- end }}

{{- if .Values.bitcoinReorganization.enabled }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "stacks-action-operator.fullname" . }}-reorganization
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    count/bitcoinreorganizations.actions.stacks.org: "64"
{{- end }}
