apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "stacks-action-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stacks-action-operator.labels" . | nindent 4 }}
rules:
  {{- range $kind, $enabled := dict "bitcoinblockgenerations" .Values.bitcoinGeneration.enabled "bitcoinreorganizations" .Values.bitcoinReorganization.enabled }}
  {{- if $enabled }}
  - apiGroups: ["actions.stacks.org"]
    resources: [{{ $kind | quote }}]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["actions.stacks.org"]
    resources: [{{ printf "%s/status" $kind | quote }}]
    verbs: ["get", "patch"]
  {{- end }}
  {{- end }}
  - apiGroups: ["network.stacks.org"]
    resources: ["stacksnetworks"]
    verbs: ["get"]
  - apiGroups: ["bitcoin.stacks.org"]
    resources: ["bitcoinblockproductions", "bitcoinproductiontargets"]
    verbs: ["get"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "stacks-action-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stacks-action-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stacks-action-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "stacks-action-operator.fullname" . }}
