//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	actionsv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/actions/v1alpha2"
	commonv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/common/v1alpha2"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinActionReservation) DeepCopyInto(out *BitcoinActionReservation) {
	*out = *in
	out.Request = in.Request
	if in.Generation != nil {
		in, out := &in.Generation, &out.Generation
		*out = new(actionsv1alpha2.BitcoinBlockGenerationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Reorganization != nil {
		in, out := &in.Reorganization, &out.Reorganization
		*out = new(actionsv1alpha2.BitcoinReorganizationSpec)
		**out = **in
	}
	out.Network = in.Network
	out.Target = in.Target
	out.Runtime = in.Runtime
	in.AdmittedAt.DeepCopyInto(&out.AdmittedAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.NextDispatchAt != nil {
		in, out := &in.NextDispatchAt, &out.NextDispatchAt
		*out = (*in).DeepCopy()
	}
	if in.LastCompletedAt != nil {
		in, out := &in.LastCompletedAt, &out.LastCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.OriginalChain != nil {
		in, out := &in.OriginalChain, &out.OriginalChain
		*out = new(actionsv1alpha2.BitcoinChainPoint)
		**out = **in
	}
	if in.ForkParent != nil {
		in, out := &in.ForkParent, &out.ForkParent
		*out = new(actionsv1alpha2.BitcoinChainPoint)
		**out = **in
	}
	if in.AcceptedChain != nil {
		in, out := &in.AcceptedChain, &out.AcceptedChain
		*out = new(actionsv1alpha2.BitcoinChainPoint)
		**out = **in
	}
	if in.ReplacementBlockHashes != nil {
		in, out := &in.ReplacementBlockHashes, &out.ReplacementBlockHashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FinalChain != nil {
		in, out := &in.FinalChain, &out.FinalChain
		*out = new(actionsv1alpha2.BitcoinChainPoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinActionReservation.
func (in *BitcoinActionReservation) DeepCopy() *BitcoinActionReservation {
	if in == nil {
		return nil
	}
	out := new(BitcoinActionReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinActiveOverride) DeepCopyInto(out *BitcoinActiveOverride) {
	*out = *in
	out.Override = in.Override
	out.Production = in.Production
	in.Schedule.DeepCopyInto(&out.Schedule)
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinActiveOverride.
func (in *BitcoinActiveOverride) DeepCopy() *BitcoinActiveOverride {
	if in == nil {
		return nil
	}
	out := new(BitcoinActiveOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinArmedRPC) DeepCopyInto(out *BitcoinArmedRPC) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	out.Reservation = in.Reservation
	out.Target = in.Target
	if in.Wallet != nil {
		in, out := &in.Wallet, &out.Wallet
		*out = new(BitcoinWalletOperation)
		**out = **in
	}
	if in.Offer != nil {
		in, out := &in.Offer, &out.Offer
		*out = new(BitcoinBlockOffer)
		(*in).DeepCopyInto(*out)
	}
	in.ArmedAt.DeepCopyInto(&out.ArmedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinArmedRPC.
func (in *BitcoinArmedRPC) DeepCopy() *BitcoinArmedRPC {
	if in == nil {
		return nil
	}
	out := new(BitcoinArmedRPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBaselineStatus) DeepCopyInto(out *BitcoinBaselineStatus) {
	*out = *in
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	if in.SelectedTarget != nil {
		in, out := &in.SelectedTarget, &out.SelectedTarget
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Receipts != nil {
		in, out := &in.Receipts, &out.Receipts
		*out = make([]BitcoinReceiptCursor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBaselineStatus.
func (in *BitcoinBaselineStatus) DeepCopy() *BitcoinBaselineStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinBaselineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockOffer) DeepCopyInto(out *BitcoinBlockOffer) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	out.Initialization = in.Initialization
	out.Production = in.Production
	out.Wallet = in.Wallet
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockOffer.
func (in *BitcoinBlockOffer) DeepCopy() *BitcoinBlockOffer {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockOffer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProduction) DeepCopyInto(out *BitcoinBlockProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProduction.
func (in *BitcoinBlockProduction) DeepCopy() *BitcoinBlockProduction {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionList) DeepCopyInto(out *BitcoinBlockProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionList.
func (in *BitcoinBlockProductionList) DeepCopy() *BitcoinBlockProductionList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionSpec) DeepCopyInto(out *BitcoinBlockProductionSpec) {
	*out = *in
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(BitcoinBlockScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = new([]ProductionTarget)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ProductionTarget, len(*in))
			copy(*out, *in)
		}
	}
	if in.PayoutWalletRef != nil {
		in, out := &in.PayoutWalletRef, &out.PayoutWalletRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(Initialization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionSpec.
func (in *BitcoinBlockProductionSpec) DeepCopy() *BitcoinBlockProductionSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockSchedule) DeepCopyInto(out *BitcoinBlockSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockSchedule.
func (in *BitcoinBlockSchedule) DeepCopy() *BitcoinBlockSchedule {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleList) DeepCopyInto(out *BitcoinBlockScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleList.
func (in *BitcoinBlockScheduleList) DeepCopy() *BitcoinBlockScheduleList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleOverride) DeepCopyInto(out *BitcoinBlockScheduleOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleOverride.
func (in *BitcoinBlockScheduleOverride) DeepCopy() *BitcoinBlockScheduleOverride {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockScheduleOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleOverrideList) DeepCopyInto(out *BitcoinBlockScheduleOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockScheduleOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleOverrideList.
func (in *BitcoinBlockScheduleOverrideList) DeepCopy() *BitcoinBlockScheduleOverrideList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockScheduleOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleOverrideSpec) DeepCopyInto(out *BitcoinBlockScheduleOverrideSpec) {
	*out = *in
	out.ProductionRef = in.ProductionRef
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(BitcoinBlockScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleOverrideSpec.
func (in *BitcoinBlockScheduleOverrideSpec) DeepCopy() *BitcoinBlockScheduleOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleOverrideStatus) DeepCopyInto(out *BitcoinBlockScheduleOverrideStatus) {
	*out = *in
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(BitcoinActiveOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingExpiresAt != nil {
		in, out := &in.PendingExpiresAt, &out.PendingExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleOverrideStatus.
func (in *BitcoinBlockScheduleOverrideStatus) DeepCopy() *BitcoinBlockScheduleOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleOverrideStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleSpec) DeepCopyInto(out *BitcoinBlockScheduleSpec) {
	*out = *in
	in.Cadence.DeepCopyInto(&out.Cadence)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleSpec.
func (in *BitcoinBlockScheduleSpec) DeepCopy() *BitcoinBlockScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinControlAcknowledgement) DeepCopyInto(out *BitcoinControlAcknowledgement) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	in.HeartbeatAt.DeepCopyInto(&out.HeartbeatAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinControlAcknowledgement.
func (in *BitcoinControlAcknowledgement) DeepCopy() *BitcoinControlAcknowledgement {
	if in == nil {
		return nil
	}
	out := new(BitcoinControlAcknowledgement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinDrainStatus) DeepCopyInto(out *BitcoinDrainStatus) {
	*out = *in
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinDrainStatus.
func (in *BitcoinDrainStatus) DeepCopy() *BitcoinDrainStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinDrainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinExecution) DeepCopyInto(out *BitcoinExecution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinExecution.
func (in *BitcoinExecution) DeepCopy() *BitcoinExecution {
	if in == nil {
		return nil
	}
	out := new(BitcoinExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinExecution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinExecutionList) DeepCopyInto(out *BitcoinExecutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinExecutionList.
func (in *BitcoinExecutionList) DeepCopy() *BitcoinExecutionList {
	if in == nil {
		return nil
	}
	out := new(BitcoinExecutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinExecutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinExecutionSpec) DeepCopyInto(out *BitcoinExecutionSpec) {
	*out = *in
	out.Participant = in.Participant
	if in.Offer != nil {
		in, out := &in.Offer, &out.Offer
		*out = new(BitcoinBlockOffer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinExecutionSpec.
func (in *BitcoinExecutionSpec) DeepCopy() *BitcoinExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinExecutionStatus) DeepCopyInto(out *BitcoinExecutionStatus) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(BitcoinActionReservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Reservation != nil {
		in, out := &in.Reservation, &out.Reservation
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Armed != nil {
		in, out := &in.Armed, &out.Armed
		*out = new(BitcoinArmedRPC)
		(*in).DeepCopyInto(*out)
	}
	if in.LastReceipt != nil {
		in, out := &in.LastReceipt, &out.LastReceipt
		*out = new(BitcoinRPCReceipt)
		(*in).DeepCopyInto(*out)
	}
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(BitcoinControlAcknowledgement)
		(*in).DeepCopyInto(*out)
	}
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(BitcoinDrainStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingWalletRemoval != nil {
		in, out := &in.PendingWalletRemoval, &out.PendingWalletRemoval
		*out = new(BitcoinWalletOperation)
		**out = **in
	}
	if in.Observation != nil {
		in, out := &in.Observation, &out.Observation
		*out = new(BitcoinObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinExecutionStatus.
func (in *BitcoinExecutionStatus) DeepCopy() *BitcoinExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinFundingCount) DeepCopyInto(out *BitcoinFundingCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinFundingCount.
func (in *BitcoinFundingCount) DeepCopy() *BitcoinFundingCount {
	if in == nil {
		return nil
	}
	out := new(BitcoinFundingCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinInitialization) DeepCopyInto(out *BitcoinInitialization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinInitialization.
func (in *BitcoinInitialization) DeepCopy() *BitcoinInitialization {
	if in == nil {
		return nil
	}
	out := new(BitcoinInitialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinInitialization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinInitializationList) DeepCopyInto(out *BitcoinInitializationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinInitialization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinInitializationList.
func (in *BitcoinInitializationList) DeepCopy() *BitcoinInitializationList {
	if in == nil {
		return nil
	}
	out := new(BitcoinInitializationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinInitializationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinInitializationSpec) DeepCopyInto(out *BitcoinInitializationSpec) {
	*out = *in
	out.Genesis = in.Genesis
	out.Production = in.Production
	out.Target = in.Target
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
	if in.MinerWallets != nil {
		in, out := &in.MinerWallets, &out.MinerWallets
		*out = make([]FrozenBitcoinWallet, len(*in))
		copy(*out, *in)
	}
	out.PayoutWallet = in.PayoutWallet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinInitializationSpec.
func (in *BitcoinInitializationSpec) DeepCopy() *BitcoinInitializationSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinInitializationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinInitializationStatus) DeepCopyInto(out *BitcoinInitializationStatus) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(BitcoinActiveOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(BitcoinBaselineStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Production != nil {
		in, out := &in.Production, &out.Production
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.NextOpportunityAt != nil {
		in, out := &in.NextOpportunityAt, &out.NextOpportunityAt
		*out = (*in).DeepCopy()
	}
	if in.Offer != nil {
		in, out := &in.Offer, &out.Offer
		*out = new(BitcoinBlockOffer)
		(*in).DeepCopyInto(*out)
	}
	if in.Funded != nil {
		in, out := &in.Funded, &out.Funded
		*out = make([]BitcoinFundingCount, len(*in))
		copy(*out, *in)
	}
	if in.FirstCeilingObservedAt != nil {
		in, out := &in.FirstCeilingObservedAt, &out.FirstCeilingObservedAt
		*out = (*in).DeepCopy()
	}
	if in.PreparedAt != nil {
		in, out := &in.PreparedAt, &out.PreparedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinInitializationStatus.
func (in *BitcoinInitializationStatus) DeepCopy() *BitcoinInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNode) DeepCopyInto(out *BitcoinNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNode.
func (in *BitcoinNode) DeepCopy() *BitcoinNode {
	if in == nil {
		return nil
	}
	out := new(BitcoinNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeList) DeepCopyInto(out *BitcoinNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeList.
func (in *BitcoinNodeList) DeepCopy() *BitcoinNodeList {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeSpec) DeepCopyInto(out *BitcoinNodeSpec) {
	*out = *in
	in.ActorFields.DeepCopyInto(&out.ActorFields)
	in.WorkerFields.DeepCopyInto(&out.WorkerFields)
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = new(commonv1alpha2.Peers)
		(*in).DeepCopyInto(*out)
	}
	if in.WalletRefs != nil {
		in, out := &in.WalletRefs, &out.WalletRefs
		*out = new([]commonv1alpha2.NameRef)
		if **in != nil {
			in, out := *in, *out
			*out = make([]commonv1alpha2.NameRef, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeSpec.
func (in *BitcoinNodeSpec) DeepCopy() *BitcoinNodeSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinObservation) DeepCopyInto(out *BitcoinObservation) {
	*out = *in
	out.Target = in.Target
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Wallets != nil {
		in, out := &in.Wallets, &out.Wallets
		*out = make([]BitcoinWalletObservation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinObservation.
func (in *BitcoinObservation) DeepCopy() *BitcoinObservation {
	if in == nil {
		return nil
	}
	out := new(BitcoinObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinRPCReceipt) DeepCopyInto(out *BitcoinRPCReceipt) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	in.ReceivedAt.DeepCopyInto(&out.ReceivedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinRPCReceipt.
func (in *BitcoinRPCReceipt) DeepCopy() *BitcoinRPCReceipt {
	if in == nil {
		return nil
	}
	out := new(BitcoinRPCReceipt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinReceiptCursor) DeepCopyInto(out *BitcoinReceiptCursor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinReceiptCursor.
func (in *BitcoinReceiptCursor) DeepCopy() *BitcoinReceiptCursor {
	if in == nil {
		return nil
	}
	out := new(BitcoinReceiptCursor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinScheduledTarget) DeepCopyInto(out *BitcoinScheduledTarget) {
	*out = *in
	out.Participant = in.Participant
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinScheduledTarget.
func (in *BitcoinScheduledTarget) DeepCopy() *BitcoinScheduledTarget {
	if in == nil {
		return nil
	}
	out := new(BitcoinScheduledTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinSchedulingStatus) DeepCopyInto(out *BitcoinSchedulingStatus) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = new(BitcoinActiveOverride)
		(*in).DeepCopyInto(*out)
	}
	out.Initialization = in.Initialization
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(BitcoinBlockScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]BitcoinScheduledTarget, len(*in))
		copy(*out, *in)
	}
	if in.NextOpportunityAt != nil {
		in, out := &in.NextOpportunityAt, &out.NextOpportunityAt
		*out = (*in).DeepCopy()
	}
	if in.LastAcknowledgedAt != nil {
		in, out := &in.LastAcknowledgedAt, &out.LastAcknowledgedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinSchedulingStatus.
func (in *BitcoinSchedulingStatus) DeepCopy() *BitcoinSchedulingStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinSchedulingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinTargetIdentity) DeepCopyInto(out *BitcoinTargetIdentity) {
	*out = *in
	out.Participant = in.Participant
	out.Pod = in.Pod
	out.Configuration = in.Configuration
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinTargetIdentity.
func (in *BitcoinTargetIdentity) DeepCopy() *BitcoinTargetIdentity {
	if in == nil {
		return nil
	}
	out := new(BitcoinTargetIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWallet) DeepCopyInto(out *BitcoinWallet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWallet.
func (in *BitcoinWallet) DeepCopy() *BitcoinWallet {
	if in == nil {
		return nil
	}
	out := new(BitcoinWallet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinWallet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWalletList) DeepCopyInto(out *BitcoinWalletList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinWallet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWalletList.
func (in *BitcoinWalletList) DeepCopy() *BitcoinWalletList {
	if in == nil {
		return nil
	}
	out := new(BitcoinWalletList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinWalletList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWalletObservation) DeepCopyInto(out *BitcoinWalletObservation) {
	*out = *in
	out.Wallet = in.Wallet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWalletObservation.
func (in *BitcoinWalletObservation) DeepCopy() *BitcoinWalletObservation {
	if in == nil {
		return nil
	}
	out := new(BitcoinWalletObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWalletOperation) DeepCopyInto(out *BitcoinWalletOperation) {
	*out = *in
	out.Wallet = in.Wallet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWalletOperation.
func (in *BitcoinWalletOperation) DeepCopy() *BitcoinWalletOperation {
	if in == nil {
		return nil
	}
	out := new(BitcoinWalletOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWalletSpec) DeepCopyInto(out *BitcoinWalletSpec) {
	*out = *in
	if in.WalletName != nil {
		in, out := &in.WalletName, &out.WalletName
		*out = new(string)
		**out = **in
	}
	if in.KeySource != nil {
		in, out := &in.KeySource, &out.KeySource
		*out = new(WalletKeySource)
		(*in).DeepCopyInto(*out)
	}
	if in.WatchOnly != nil {
		in, out := &in.WatchOnly, &out.WatchOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWalletSpec.
func (in *BitcoinWalletSpec) DeepCopy() *BitcoinWalletSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinWalletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cadence) DeepCopyInto(out *Cadence) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
	if in.MinimumInterval != nil {
		in, out := &in.MinimumInterval, &out.MinimumInterval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
	if in.MaximumInterval != nil {
		in, out := &in.MaximumInterval, &out.MaximumInterval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cadence.
func (in *Cadence) DeepCopy() *Cadence {
	if in == nil {
		return nil
	}
	out := new(Cadence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenBitcoinWallet) DeepCopyInto(out *FrozenBitcoinWallet) {
	*out = *in
	out.Wallet = in.Wallet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenBitcoinWallet.
func (in *FrozenBitcoinWallet) DeepCopy() *FrozenBitcoinWallet {
	if in == nil {
		return nil
	}
	out := new(FrozenBitcoinWallet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Initialization) DeepCopyInto(out *Initialization) {
	*out = *in
	out.TargetNodeRef = in.TargetNodeRef
	if in.MinerWalletRefs != nil {
		in, out := &in.MinerWalletRefs, &out.MinerWalletRefs
		*out = new([]commonv1alpha2.NameRef)
		if **in != nil {
			in, out := *in, *out
			*out = make([]commonv1alpha2.NameRef, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Initialization.
func (in *Initialization) DeepCopy() *Initialization {
	if in == nil {
		return nil
	}
	out := new(Initialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductionTarget) DeepCopyInto(out *ProductionTarget) {
	*out = *in
	out.NodeRef = in.NodeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductionTarget.
func (in *ProductionTarget) DeepCopy() *ProductionTarget {
	if in == nil {
		return nil
	}
	out := new(ProductionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WalletKeySource) DeepCopyInto(out *WalletKeySource) {
	*out = *in
	if in.Generate != nil {
		in, out := &in.Generate, &out.Generate
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(commonv1alpha2.SecretKeyRef)
		**out = **in
	}
	if in.StacksMinerAccountRef != nil {
		in, out := &in.StacksMinerAccountRef, &out.StacksMinerAccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WalletKeySource.
func (in *WalletKeySource) DeepCopy() *WalletKeySource {
	if in == nil {
		return nil
	}
	out := new(WalletKeySource)
	in.DeepCopyInto(out)
	return out
}
