//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	commonv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/common/v1alpha2"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProduction) DeepCopyInto(out *BitcoinBlockProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProduction.
func (in *BitcoinBlockProduction) DeepCopy() *BitcoinBlockProduction {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionList) DeepCopyInto(out *BitcoinBlockProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionList.
func (in *BitcoinBlockProductionList) DeepCopy() *BitcoinBlockProductionList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockProductionSpec) DeepCopyInto(out *BitcoinBlockProductionSpec) {
	*out = *in
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(BitcoinBlockScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = new([]ProductionTarget)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ProductionTarget, len(*in))
			copy(*out, *in)
		}
	}
	if in.PayoutWalletRef != nil {
		in, out := &in.PayoutWalletRef, &out.PayoutWalletRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(Initialization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockProductionSpec.
func (in *BitcoinBlockProductionSpec) DeepCopy() *BitcoinBlockProductionSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockProductionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockSchedule) DeepCopyInto(out *BitcoinBlockSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockSchedule.
func (in *BitcoinBlockSchedule) DeepCopy() *BitcoinBlockSchedule {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleList) DeepCopyInto(out *BitcoinBlockScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleList.
func (in *BitcoinBlockScheduleList) DeepCopy() *BitcoinBlockScheduleList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockScheduleSpec) DeepCopyInto(out *BitcoinBlockScheduleSpec) {
	*out = *in
	in.Cadence.DeepCopyInto(&out.Cadence)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockScheduleSpec.
func (in *BitcoinBlockScheduleSpec) DeepCopy() *BitcoinBlockScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNode) DeepCopyInto(out *BitcoinNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNode.
func (in *BitcoinNode) DeepCopy() *BitcoinNode {
	if in == nil {
		return nil
	}
	out := new(BitcoinNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeList) DeepCopyInto(out *BitcoinNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeList.
func (in *BitcoinNodeList) DeepCopy() *BitcoinNodeList {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeSpec) DeepCopyInto(out *BitcoinNodeSpec) {
	*out = *in
	in.ActorFields.DeepCopyInto(&out.ActorFields)
	in.WorkerFields.DeepCopyInto(&out.WorkerFields)
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = new(commonv1alpha2.Peers)
		(*in).DeepCopyInto(*out)
	}
	if in.WalletRefs != nil {
		in, out := &in.WalletRefs, &out.WalletRefs
		*out = new([]commonv1alpha2.NameRef)
		if **in != nil {
			in, out := *in, *out
			*out = make([]commonv1alpha2.NameRef, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeSpec.
func (in *BitcoinNodeSpec) DeepCopy() *BitcoinNodeSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWallet) DeepCopyInto(out *BitcoinWallet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWallet.
func (in *BitcoinWallet) DeepCopy() *BitcoinWallet {
	if in == nil {
		return nil
	}
	out := new(BitcoinWallet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinWallet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWalletList) DeepCopyInto(out *BitcoinWalletList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinWallet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWalletList.
func (in *BitcoinWalletList) DeepCopy() *BitcoinWalletList {
	if in == nil {
		return nil
	}
	out := new(BitcoinWalletList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinWalletList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinWalletSpec) DeepCopyInto(out *BitcoinWalletSpec) {
	*out = *in
	if in.WalletName != nil {
		in, out := &in.WalletName, &out.WalletName
		*out = new(string)
		**out = **in
	}
	if in.KeySource != nil {
		in, out := &in.KeySource, &out.KeySource
		*out = new(WalletKeySource)
		(*in).DeepCopyInto(*out)
	}
	if in.WatchOnly != nil {
		in, out := &in.WatchOnly, &out.WatchOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinWalletSpec.
func (in *BitcoinWalletSpec) DeepCopy() *BitcoinWalletSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinWalletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cadence) DeepCopyInto(out *Cadence) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
	if in.MinimumInterval != nil {
		in, out := &in.MinimumInterval, &out.MinimumInterval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
	if in.MaximumInterval != nil {
		in, out := &in.MaximumInterval, &out.MaximumInterval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cadence.
func (in *Cadence) DeepCopy() *Cadence {
	if in == nil {
		return nil
	}
	out := new(Cadence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Initialization) DeepCopyInto(out *Initialization) {
	*out = *in
	out.TargetNodeRef = in.TargetNodeRef
	if in.MinerWalletRefs != nil {
		in, out := &in.MinerWalletRefs, &out.MinerWalletRefs
		*out = new([]commonv1alpha2.NameRef)
		if **in != nil {
			in, out := *in, *out
			*out = make([]commonv1alpha2.NameRef, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Initialization.
func (in *Initialization) DeepCopy() *Initialization {
	if in == nil {
		return nil
	}
	out := new(Initialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductionTarget) DeepCopyInto(out *ProductionTarget) {
	*out = *in
	out.NodeRef = in.NodeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductionTarget.
func (in *ProductionTarget) DeepCopy() *ProductionTarget {
	if in == nil {
		return nil
	}
	out := new(ProductionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WalletKeySource) DeepCopyInto(out *WalletKeySource) {
	*out = *in
	if in.Generate != nil {
		in, out := &in.Generate, &out.Generate
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(commonv1alpha2.SecretKeyRef)
		**out = **in
	}
	if in.StacksMinerAccountRef != nil {
		in, out := &in.StacksMinerAccountRef, &out.StacksMinerAccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WalletKeySource.
func (in *WalletKeySource) DeepCopy() *WalletKeySource {
	if in == nil {
		return nil
	}
	out := new(WalletKeySource)
	in.DeepCopyInto(out)
	return out
}
