//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	bitcoinv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/bitcoin/v1alpha2"
	commonv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/common/v1alpha2"
	stacksv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/stacks/v1alpha2"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorResources) DeepCopyInto(out *ActorResources) {
	*out = *in
	if in.Bitcoin != nil {
		in, out := &in.Bitcoin, &out.Bitcoin
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksNode != nil {
		in, out := &in.StacksNode, &out.StacksNode
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksSigner != nil {
		in, out := &in.StacksSigner, &out.StacksSigner
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorResources.
func (in *ActorResources) DeepCopy() *ActorResources {
	if in == nil {
		return nil
	}
	out := new(ActorResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Admission) DeepCopyInto(out *Admission) {
	*out = *in
	in.Configuration.DeepCopyInto(&out.Configuration)
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Admission.
func (in *Admission) DeepCopy() *Admission {
	if in == nil {
		return nil
	}
	out := new(Admission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allocation) DeepCopyInto(out *Allocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allocation.
func (in *Allocation) DeepCopy() *Allocation {
	if in == nil {
		return nil
	}
	out := new(Allocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootstrap) DeepCopyInto(out *Bootstrap) {
	*out = *in
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]Gate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]BootstrapRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootstrap.
func (in *Bootstrap) DeepCopy() *Bootstrap {
	if in == nil {
		return nil
	}
	out := new(Bootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapRequirement) DeepCopyInto(out *BootstrapRequirement) {
	*out = *in
	out.Participant = in.Participant
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
	if in.AmountMicroSTX != nil {
		in, out := &in.AmountMicroSTX, &out.AmountMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
	if in.LockCycles != nil {
		in, out := &in.LockCycles, &out.LockCycles
		*out = new(int32)
		**out = **in
	}
	if in.RenewWhenRemainingCycles != nil {
		in, out := &in.RenewWhenRemainingCycles, &out.RenewWhenRemainingCycles
		*out = new(int32)
		**out = **in
	}
	if in.BitcoinPayoutWallet != nil {
		in, out := &in.BitcoinPayoutWallet, &out.BitcoinPayoutWallet
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.BitcoinInitialization != nil {
		in, out := &in.BitcoinInitialization, &out.BitcoinInitialization
		*out = new(bitcoinv1alpha2.Initialization)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryInitialization != nil {
		in, out := &in.RegistryInitialization, &out.RegistryInitialization
		*out = new(stacksv1alpha2.RegistryInitialization)
		(*in).DeepCopyInto(*out)
	}
	if in.Accounts != nil {
		in, out := &in.Accounts, &out.Accounts
		*out = make([]PublicAccount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapRequirement.
func (in *BootstrapRequirement) DeepCopy() *BootstrapRequirement {
	if in == nil {
		return nil
	}
	out := new(BootstrapRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Chain) DeepCopyInto(out *Chain) {
	*out = *in
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]Epoch, len(*in))
		copy(*out, *in)
	}
	out.PoX = in.PoX
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]Allocation, len(*in))
		copy(*out, *in)
	}
	in.Contracts.DeepCopyInto(&out.Contracts)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chain.
func (in *Chain) DeepCopy() *Chain {
	if in == nil {
		return nil
	}
	out := new(Chain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	if in.BitcoinNode != nil {
		in, out := &in.BitcoinNode, &out.BitcoinNode
		*out = new(bitcoinv1alpha2.BitcoinNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksNode != nil {
		in, out := &in.StacksNode, &out.StacksNode
		*out = new(stacksv1alpha2.StacksNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksSigner != nil {
		in, out := &in.StacksSigner, &out.StacksSigner
		*out = new(stacksv1alpha2.StacksSignerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksStacker != nil {
		in, out := &in.StacksStacker, &out.StacksStacker
		*out = new(stacksv1alpha2.StacksStackerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksFaucet != nil {
		in, out := &in.StacksFaucet, &out.StacksFaucet
		*out = new(stacksv1alpha2.StacksFaucetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksContractSet != nil {
		in, out := &in.StacksContractSet, &out.StacksContractSet
		*out = new(stacksv1alpha2.StacksContractSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksTransactionProduction != nil {
		in, out := &in.StacksTransactionProduction, &out.StacksTransactionProduction
		*out = new(stacksv1alpha2.StacksTransactionProductionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BitcoinBlockProduction != nil {
		in, out := &in.BitcoinBlockProduction, &out.BitcoinBlockProduction
		*out = new(bitcoinv1alpha2.BitcoinBlockProductionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractBindings) DeepCopyInto(out *ContractBindings) {
	*out = *in
	if in.SourceHashes != nil {
		in, out := &in.SourceHashes, &out.SourceHashes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractBindings.
func (in *ContractBindings) DeepCopy() *ContractBindings {
	if in == nil {
		return nil
	}
	out := new(ContractBindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Control) DeepCopyInto(out *Control) {
	*out = *in
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = new(bool)
		**out = **in
	}
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Control.
func (in *Control) DeepCopy() *Control {
	if in == nil {
		return nil
	}
	out := new(Control)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Defaults) DeepCopyInto(out *Defaults) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(Images)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(commonv1alpha2.Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.ActorResources != nil {
		in, out := &in.ActorResources, &out.ActorResources
		*out = new(ActorResources)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerPlacement != nil {
		in, out := &in.WorkerPlacement, &out.WorkerPlacement
		*out = new(commonv1alpha2.Placement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Defaults.
func (in *Defaults) DeepCopy() *Defaults {
	if in == nil {
		return nil
	}
	out := new(Defaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Definition) DeepCopyInto(out *Definition) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(Configuration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Definition.
func (in *Definition) DeepCopy() *Definition {
	if in == nil {
		return nil
	}
	out := new(Definition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Epoch) DeepCopyInto(out *Epoch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Epoch.
func (in *Epoch) DeepCopy() *Epoch {
	if in == nil {
		return nil
	}
	out := new(Epoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gate) DeepCopyInto(out *Gate) {
	*out = *in
	if in.TargetCycle != nil {
		in, out := &in.TargetCycle, &out.TargetCycle
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gate.
func (in *Gate) DeepCopy() *Gate {
	if in == nil {
		return nil
	}
	out := new(Gate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisAllocation) DeepCopyInto(out *GenesisAllocation) {
	*out = *in
	out.AccountRef = in.AccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisAllocation.
func (in *GenesisAllocation) DeepCopy() *GenesisAllocation {
	if in == nil {
		return nil
	}
	out := new(GenesisAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisInput) DeepCopyInto(out *GenesisInput) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]GenesisAllocation, len(*in))
		copy(*out, *in)
	}
	if in.PoX != nil {
		in, out := &in.PoX, &out.PoX
		*out = new(PoX)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisInput.
func (in *GenesisInput) DeepCopy() *GenesisInput {
	if in == nil {
		return nil
	}
	out := new(GenesisInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisSource) DeepCopyInto(out *GenesisSource) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisSource.
func (in *GenesisSource) DeepCopy() *GenesisSource {
	if in == nil {
		return nil
	}
	out := new(GenesisSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Images) DeepCopyInto(out *Images) {
	*out = *in
	if in.Bitcoin != nil {
		in, out := &in.Bitcoin, &out.Bitcoin
		*out = new(string)
		**out = **in
	}
	if in.StacksNode != nil {
		in, out := &in.StacksNode, &out.StacksNode
		*out = new(string)
		**out = **in
	}
	if in.StacksSigner != nil {
		in, out := &in.StacksSigner, &out.StacksSigner
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Images.
func (in *Images) DeepCopy() *Images {
	if in == nil {
		return nil
	}
	out := new(Images)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIdentity) DeepCopyInto(out *InstanceIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIdentity.
func (in *InstanceIdentity) DeepCopy() *InstanceIdentity {
	if in == nil {
		return nil
	}
	out := new(InstanceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Participant) DeepCopyInto(out *Participant) {
	*out = *in
	in.Definition.DeepCopyInto(&out.Definition)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(Control)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Participant.
func (in *Participant) DeepCopy() *Participant {
	if in == nil {
		return nil
	}
	out := new(Participant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParticipantStatus) DeepCopyInto(out *ParticipantStatus) {
	*out = *in
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(Admission)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParticipantStatus.
func (in *ParticipantStatus) DeepCopy() *ParticipantStatus {
	if in == nil {
		return nil
	}
	out := new(ParticipantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoX) DeepCopyInto(out *PoX) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoX.
func (in *PoX) DeepCopy() *PoX {
	if in == nil {
		return nil
	}
	out := new(PoX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicAccount) DeepCopyInto(out *PublicAccount) {
	*out = *in
	out.Binding = in.Binding
	out.Identity = in.Identity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicAccount.
func (in *PublicAccount) DeepCopy() *PublicAccount {
	if in == nil {
		return nil
	}
	out := new(PublicAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksEpochSchedule) DeepCopyInto(out *StacksEpochSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksEpochSchedule.
func (in *StacksEpochSchedule) DeepCopy() *StacksEpochSchedule {
	if in == nil {
		return nil
	}
	out := new(StacksEpochSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksEpochSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksEpochScheduleList) DeepCopyInto(out *StacksEpochScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksEpochSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksEpochScheduleList.
func (in *StacksEpochScheduleList) DeepCopy() *StacksEpochScheduleList {
	if in == nil {
		return nil
	}
	out := new(StacksEpochScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksEpochScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksEpochScheduleSpec) DeepCopyInto(out *StacksEpochScheduleSpec) {
	*out = *in
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]Epoch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksEpochScheduleSpec.
func (in *StacksEpochScheduleSpec) DeepCopy() *StacksEpochScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(StacksEpochScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesis) DeepCopyInto(out *StacksGenesis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesis.
func (in *StacksGenesis) DeepCopy() *StacksGenesis {
	if in == nil {
		return nil
	}
	out := new(StacksGenesis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksGenesis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisList) DeepCopyInto(out *StacksGenesisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksGenesis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisList.
func (in *StacksGenesisList) DeepCopy() *StacksGenesisList {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksGenesisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisSpec) DeepCopyInto(out *StacksGenesisSpec) {
	*out = *in
	in.Chain.DeepCopyInto(&out.Chain)
	in.Source.DeepCopyInto(&out.Source)
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisSpec.
func (in *StacksGenesisSpec) DeepCopy() *StacksGenesisSpec {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetwork) DeepCopyInto(out *StacksNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetwork.
func (in *StacksNetwork) DeepCopy() *StacksNetwork {
	if in == nil {
		return nil
	}
	out := new(StacksNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkList) DeepCopyInto(out *StacksNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkList.
func (in *StacksNetworkList) DeepCopy() *StacksNetworkList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkParticipant) DeepCopyInto(out *StacksNetworkParticipant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkParticipant.
func (in *StacksNetworkParticipant) DeepCopy() *StacksNetworkParticipant {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkParticipant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkParticipant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkParticipantList) DeepCopyInto(out *StacksNetworkParticipantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetworkParticipant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkParticipantList.
func (in *StacksNetworkParticipantList) DeepCopy() *StacksNetworkParticipantList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkParticipantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkParticipantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkParticipantSpec) DeepCopyInto(out *StacksNetworkParticipantSpec) {
	*out = *in
	out.Source = in.Source
	in.Configuration.DeepCopyInto(&out.Configuration)
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(Control)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkParticipantSpec.
func (in *StacksNetworkParticipantSpec) DeepCopy() *StacksNetworkParticipantSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkParticipantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkSpec) DeepCopyInto(out *StacksNetworkSpec) {
	*out = *in
	if in.EpochScheduleRef != nil {
		in, out := &in.EpochScheduleRef, &out.EpochScheduleRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.EpochSchedule != nil {
		in, out := &in.EpochSchedule, &out.EpochSchedule
		*out = new(StacksEpochScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(GenesisInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(Defaults)
		(*in).DeepCopyInto(*out)
	}
	if in.Participants != nil {
		in, out := &in.Participants, &out.Participants
		*out = make([]Participant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpectedInputDigest != nil {
		in, out := &in.ExpectedInputDigest, &out.ExpectedInputDigest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkSpec.
func (in *StacksNetworkSpec) DeepCopy() *StacksNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkStatus) DeepCopyInto(out *StacksNetworkStatus) {
	*out = *in
	if in.GenesisRef != nil {
		in, out := &in.GenesisRef, &out.GenesisRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Identities != nil {
		in, out := &in.Identities, &out.Identities
		*out = make([]InstanceIdentity, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkStatus.
func (in *StacksNetworkStatus) DeepCopy() *StacksNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkStatus)
	in.DeepCopyInto(out)
	return out
}
