//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	bitcoinv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/bitcoin/v1alpha2"
	commonv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/common/v1alpha2"
	stacksv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/stacks/v1alpha2"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorResources) DeepCopyInto(out *ActorResources) {
	*out = *in
	if in.Bitcoin != nil {
		in, out := &in.Bitcoin, &out.Bitcoin
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksNode != nil {
		in, out := &in.StacksNode, &out.StacksNode
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksSigner != nil {
		in, out := &in.StacksSigner, &out.StacksSigner
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorResources.
func (in *ActorResources) DeepCopy() *ActorResources {
	if in == nil {
		return nil
	}
	out := new(ActorResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Admission) DeepCopyInto(out *Admission) {
	*out = *in
	out.Source = in.Source
	in.Configuration.DeepCopyInto(&out.Configuration)
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Admission.
func (in *Admission) DeepCopy() *Admission {
	if in == nil {
		return nil
	}
	out := new(Admission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Allocation) DeepCopyInto(out *Allocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Allocation.
func (in *Allocation) DeepCopy() *Allocation {
	if in == nil {
		return nil
	}
	out := new(Allocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinControlPodStatus) DeepCopyInto(out *BitcoinControlPodStatus) {
	*out = *in
	out.Pod = in.Pod
	out.ReplicaSet = in.ReplicaSet
	out.Deployment = in.Deployment
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinControlPodStatus.
func (in *BitcoinControlPodStatus) DeepCopy() *BitcoinControlPodStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinControlPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinControlRuntimeStatus) DeepCopyInto(out *BitcoinControlRuntimeStatus) {
	*out = *in
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]BitcoinControlPodStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinControlRuntimeStatus.
func (in *BitcoinControlRuntimeStatus) DeepCopy() *BitcoinControlRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinControlRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinRuntimeStatus) DeepCopyInto(out *BitcoinRuntimeStatus) {
	*out = *in
	if in.ExecutionRefs != nil {
		in, out := &in.ExecutionRefs, &out.ExecutionRefs
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
	if in.InitializationRef != nil {
		in, out := &in.InitializationRef, &out.InitializationRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinRuntimeStatus.
func (in *BitcoinRuntimeStatus) DeepCopy() *BitcoinRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootstrap) DeepCopyInto(out *Bootstrap) {
	*out = *in
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]Gate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]BootstrapRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootstrap.
func (in *Bootstrap) DeepCopy() *Bootstrap {
	if in == nil {
		return nil
	}
	out := new(Bootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapRequirement) DeepCopyInto(out *BootstrapRequirement) {
	*out = *in
	out.Participant = in.Participant
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
	if in.MiningEnabled != nil {
		in, out := &in.MiningEnabled, &out.MiningEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AmountMicroSTX != nil {
		in, out := &in.AmountMicroSTX, &out.AmountMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
	if in.LockCycles != nil {
		in, out := &in.LockCycles, &out.LockCycles
		*out = new(int32)
		**out = **in
	}
	if in.RenewWhenRemainingCycles != nil {
		in, out := &in.RenewWhenRemainingCycles, &out.RenewWhenRemainingCycles
		*out = new(int32)
		**out = **in
	}
	if in.BitcoinPayoutWallet != nil {
		in, out := &in.BitcoinPayoutWallet, &out.BitcoinPayoutWallet
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.BitcoinInitialization != nil {
		in, out := &in.BitcoinInitialization, &out.BitcoinInitialization
		*out = new(bitcoinv1alpha2.Initialization)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryInitialization != nil {
		in, out := &in.RegistryInitialization, &out.RegistryInitialization
		*out = new(stacksv1alpha2.RegistryInitialization)
		(*in).DeepCopyInto(*out)
	}
	if in.Accounts != nil {
		in, out := &in.Accounts, &out.Accounts
		*out = make([]PublicAccount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapRequirement.
func (in *BootstrapRequirement) DeepCopy() *BootstrapRequirement {
	if in == nil {
		return nil
	}
	out := new(BootstrapRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnHeightSample) DeepCopyInto(out *BurnHeightSample) {
	*out = *in
	out.Participant = in.Participant
	out.Pod = in.Pod
	in.FirstObservedAt.DeepCopyInto(&out.FirstObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnHeightSample.
func (in *BurnHeightSample) DeepCopy() *BurnHeightSample {
	if in == nil {
		return nil
	}
	out := new(BurnHeightSample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurnchainObservations) DeepCopyInto(out *BurnchainObservations) {
	*out = *in
	if in.Bitcoin != nil {
		in, out := &in.Bitcoin, &out.Bitcoin
		*out = new(BurnHeightSample)
		(*in).DeepCopyInto(*out)
	}
	if in.Miner != nil {
		in, out := &in.Miner, &out.Miner
		*out = new(BurnHeightSample)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurnchainObservations.
func (in *BurnchainObservations) DeepCopy() *BurnchainObservations {
	if in == nil {
		return nil
	}
	out := new(BurnchainObservations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Chain) DeepCopyInto(out *Chain) {
	*out = *in
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]Epoch, len(*in))
		copy(*out, *in)
	}
	out.PoX = in.PoX
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]Allocation, len(*in))
		copy(*out, *in)
	}
	in.Contracts.DeepCopyInto(&out.Contracts)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chain.
func (in *Chain) DeepCopy() *Chain {
	if in == nil {
		return nil
	}
	out := new(Chain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	if in.BitcoinNode != nil {
		in, out := &in.BitcoinNode, &out.BitcoinNode
		*out = new(bitcoinv1alpha2.BitcoinNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksNode != nil {
		in, out := &in.StacksNode, &out.StacksNode
		*out = new(stacksv1alpha2.StacksNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksSigner != nil {
		in, out := &in.StacksSigner, &out.StacksSigner
		*out = new(stacksv1alpha2.StacksSignerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksStacker != nil {
		in, out := &in.StacksStacker, &out.StacksStacker
		*out = new(stacksv1alpha2.StacksStackerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksFaucet != nil {
		in, out := &in.StacksFaucet, &out.StacksFaucet
		*out = new(stacksv1alpha2.StacksFaucetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksContractSet != nil {
		in, out := &in.StacksContractSet, &out.StacksContractSet
		*out = new(stacksv1alpha2.StacksContractSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksTransactionProduction != nil {
		in, out := &in.StacksTransactionProduction, &out.StacksTransactionProduction
		*out = new(stacksv1alpha2.StacksTransactionProductionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BitcoinBlockProduction != nil {
		in, out := &in.BitcoinBlockProduction, &out.BitcoinBlockProduction
		*out = new(bitcoinv1alpha2.BitcoinBlockProductionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractBindings) DeepCopyInto(out *ContractBindings) {
	*out = *in
	if in.SourceHashes != nil {
		in, out := &in.SourceHashes, &out.SourceHashes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractBindings.
func (in *ContractBindings) DeepCopy() *ContractBindings {
	if in == nil {
		return nil
	}
	out := new(ContractBindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSetObservation) DeepCopyInto(out *ContractSetObservation) {
	*out = *in
	if in.SignerPublicKeys != nil {
		in, out := &in.SignerPublicKeys, &out.SignerPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSetObservation.
func (in *ContractSetObservation) DeepCopy() *ContractSetObservation {
	if in == nil {
		return nil
	}
	out := new(ContractSetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Control) DeepCopyInto(out *Control) {
	*out = *in
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = new(bool)
		**out = **in
	}
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Control.
func (in *Control) DeepCopy() *Control {
	if in == nil {
		return nil
	}
	out := new(Control)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Defaults) DeepCopyInto(out *Defaults) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(Images)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(commonv1alpha2.Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.ActorResources != nil {
		in, out := &in.ActorResources, &out.ActorResources
		*out = new(ActorResources)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerPlacement != nil {
		in, out := &in.WorkerPlacement, &out.WorkerPlacement
		*out = new(commonv1alpha2.Placement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Defaults.
func (in *Defaults) DeepCopy() *Defaults {
	if in == nil {
		return nil
	}
	out := new(Defaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Definition) DeepCopyInto(out *Definition) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(Configuration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Definition.
func (in *Definition) DeepCopy() *Definition {
	if in == nil {
		return nil
	}
	out := new(Definition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Epoch) DeepCopyInto(out *Epoch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Epoch.
func (in *Epoch) DeepCopy() *Epoch {
	if in == nil {
		return nil
	}
	out := new(Epoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gate) DeepCopyInto(out *Gate) {
	*out = *in
	if in.TargetCycle != nil {
		in, out := &in.TargetCycle, &out.TargetCycle
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gate.
func (in *Gate) DeepCopy() *Gate {
	if in == nil {
		return nil
	}
	out := new(Gate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateObservation) DeepCopyInto(out *GateObservation) {
	*out = *in
	if in.FirstCeilingObservedAt != nil {
		in, out := &in.FirstCeilingObservedAt, &out.FirstCeilingObservedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GateObservation.
func (in *GateObservation) DeepCopy() *GateObservation {
	if in == nil {
		return nil
	}
	out := new(GateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisAllocation) DeepCopyInto(out *GenesisAllocation) {
	*out = *in
	out.AccountRef = in.AccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisAllocation.
func (in *GenesisAllocation) DeepCopy() *GenesisAllocation {
	if in == nil {
		return nil
	}
	out := new(GenesisAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisInput) DeepCopyInto(out *GenesisInput) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]GenesisAllocation, len(*in))
		copy(*out, *in)
	}
	if in.PoX != nil {
		in, out := &in.PoX, &out.PoX
		*out = new(PoX)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisInput.
func (in *GenesisInput) DeepCopy() *GenesisInput {
	if in == nil {
		return nil
	}
	out := new(GenesisInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisSource) DeepCopyInto(out *GenesisSource) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisSource.
func (in *GenesisSource) DeepCopy() *GenesisSource {
	if in == nil {
		return nil
	}
	out := new(GenesisSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Images) DeepCopyInto(out *Images) {
	*out = *in
	if in.Bitcoin != nil {
		in, out := &in.Bitcoin, &out.Bitcoin
		*out = new(string)
		**out = **in
	}
	if in.StacksNode != nil {
		in, out := &in.StacksNode, &out.StacksNode
		*out = new(string)
		**out = **in
	}
	if in.StacksSigner != nil {
		in, out := &in.StacksSigner, &out.StacksSigner
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Images.
func (in *Images) DeepCopy() *Images {
	if in == nil {
		return nil
	}
	out := new(Images)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializationStatus) DeepCopyInto(out *InitializationStatus) {
	*out = *in
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]GateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializationStatus.
func (in *InitializationStatus) DeepCopy() *InitializationStatus {
	if in == nil {
		return nil
	}
	out := new(InitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIdentity) DeepCopyInto(out *InstanceIdentity) {
	*out = *in
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(WorkerSession)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIdentity.
func (in *InstanceIdentity) DeepCopy() *InstanceIdentity {
	if in == nil {
		return nil
	}
	out := new(InstanceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservationPolicy) DeepCopyInto(out *ObservationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservationPolicy.
func (in *ObservationPolicy) DeepCopy() *ObservationPolicy {
	if in == nil {
		return nil
	}
	out := new(ObservationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Participant) DeepCopyInto(out *Participant) {
	*out = *in
	in.Definition.DeepCopyInto(&out.Definition)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(Control)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Participant.
func (in *Participant) DeepCopy() *Participant {
	if in == nil {
		return nil
	}
	out := new(Participant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParticipantRuntimeStatus) DeepCopyInto(out *ParticipantRuntimeStatus) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(StacksProtocolObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerCandidate != nil {
		in, out := &in.WorkerCandidate, &out.WorkerCandidate
		*out = new(WorkerCandidate)
		**out = **in
	}
	if in.WorkloadRefs != nil {
		in, out := &in.WorkloadRefs, &out.WorkloadRefs
		*out = make([]commonv1alpha2.Binding, len(*in))
		copy(*out, *in)
	}
	if in.ConfigRef != nil {
		in, out := &in.ConfigRef, &out.ConfigRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.EventAuthSecretRef != nil {
		in, out := &in.EventAuthSecretRef, &out.EventAuthSecretRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.RPCSecretRef != nil {
		in, out := &in.RPCSecretRef, &out.RPCSecretRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.ObserverRPCSecretRef != nil {
		in, out := &in.ObserverRPCSecretRef, &out.ObserverRPCSecretRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.ActorRPCSecretRef != nil {
		in, out := &in.ActorRPCSecretRef, &out.ActorRPCSecretRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]RuntimeEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParticipantRuntimeStatus.
func (in *ParticipantRuntimeStatus) DeepCopy() *ParticipantRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(ParticipantRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParticipantStatus) DeepCopyInto(out *ParticipantStatus) {
	*out = *in
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(Admission)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ParticipantRuntimeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BitcoinControl != nil {
		in, out := &in.BitcoinControl, &out.BitcoinControl
		*out = new(BitcoinControlRuntimeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(bitcoinv1alpha2.BitcoinSchedulingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(WorkerExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParticipantStatus.
func (in *ParticipantStatus) DeepCopy() *ParticipantStatus {
	if in == nil {
		return nil
	}
	out := new(ParticipantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoX) DeepCopyInto(out *PoX) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoX.
func (in *PoX) DeepCopy() *PoX {
	if in == nil {
		return nil
	}
	out := new(PoX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoX4EnrollmentObservation) DeepCopyInto(out *PoX4EnrollmentObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoX4EnrollmentObservation.
func (in *PoX4EnrollmentObservation) DeepCopy() *PoX4EnrollmentObservation {
	if in == nil {
		return nil
	}
	out := new(PoX4EnrollmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoX5EnrollmentObservation) DeepCopyInto(out *PoX5EnrollmentObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoX5EnrollmentObservation.
func (in *PoX5EnrollmentObservation) DeepCopy() *PoX5EnrollmentObservation {
	if in == nil {
		return nil
	}
	out := new(PoX5EnrollmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreparedSignerObservation) DeepCopyInto(out *PreparedSignerObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreparedSignerObservation.
func (in *PreparedSignerObservation) DeepCopy() *PreparedSignerObservation {
	if in == nil {
		return nil
	}
	out := new(PreparedSignerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreparedSignerSetObservation) DeepCopyInto(out *PreparedSignerSetObservation) {
	*out = *in
	if in.Signers != nil {
		in, out := &in.Signers, &out.Signers
		*out = make([]PreparedSignerObservation, len(*in))
		copy(*out, *in)
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreparedSignerSetObservation.
func (in *PreparedSignerSetObservation) DeepCopy() *PreparedSignerSetObservation {
	if in == nil {
		return nil
	}
	out := new(PreparedSignerSetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicAccount) DeepCopyInto(out *PublicAccount) {
	*out = *in
	out.Binding = in.Binding
	out.Identity = in.Identity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicAccount.
func (in *PublicAccount) DeepCopy() *PublicAccount {
	if in == nil {
		return nil
	}
	out := new(PublicAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeEndpoint) DeepCopyInto(out *RuntimeEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeEndpoint.
func (in *RuntimeEndpoint) DeepCopy() *RuntimeEndpoint {
	if in == nil {
		return nil
	}
	out := new(RuntimeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksEpochSchedule) DeepCopyInto(out *StacksEpochSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksEpochSchedule.
func (in *StacksEpochSchedule) DeepCopy() *StacksEpochSchedule {
	if in == nil {
		return nil
	}
	out := new(StacksEpochSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksEpochSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksEpochScheduleList) DeepCopyInto(out *StacksEpochScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksEpochSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksEpochScheduleList.
func (in *StacksEpochScheduleList) DeepCopy() *StacksEpochScheduleList {
	if in == nil {
		return nil
	}
	out := new(StacksEpochScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksEpochScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksEpochScheduleSpec) DeepCopyInto(out *StacksEpochScheduleSpec) {
	*out = *in
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]Epoch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksEpochScheduleSpec.
func (in *StacksEpochScheduleSpec) DeepCopy() *StacksEpochScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(StacksEpochScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesis) DeepCopyInto(out *StacksGenesis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesis.
func (in *StacksGenesis) DeepCopy() *StacksGenesis {
	if in == nil {
		return nil
	}
	out := new(StacksGenesis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksGenesis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisList) DeepCopyInto(out *StacksGenesisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksGenesis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisList.
func (in *StacksGenesisList) DeepCopy() *StacksGenesisList {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksGenesisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisSpec) DeepCopyInto(out *StacksGenesisSpec) {
	*out = *in
	in.Chain.DeepCopyInto(&out.Chain)
	in.Source.DeepCopyInto(&out.Source)
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisSpec.
func (in *StacksGenesisSpec) DeepCopy() *StacksGenesisSpec {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetwork) DeepCopyInto(out *StacksNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetwork.
func (in *StacksNetwork) DeepCopy() *StacksNetwork {
	if in == nil {
		return nil
	}
	out := new(StacksNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkList) DeepCopyInto(out *StacksNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkList.
func (in *StacksNetworkList) DeepCopy() *StacksNetworkList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkParticipant) DeepCopyInto(out *StacksNetworkParticipant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkParticipant.
func (in *StacksNetworkParticipant) DeepCopy() *StacksNetworkParticipant {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkParticipant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkParticipant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkParticipantList) DeepCopyInto(out *StacksNetworkParticipantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetworkParticipant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkParticipantList.
func (in *StacksNetworkParticipantList) DeepCopy() *StacksNetworkParticipantList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkParticipantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkParticipantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkParticipantSpec) DeepCopyInto(out *StacksNetworkParticipantSpec) {
	*out = *in
	out.Source = in.Source
	in.Configuration.DeepCopyInto(&out.Configuration)
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(Control)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkParticipantSpec.
func (in *StacksNetworkParticipantSpec) DeepCopy() *StacksNetworkParticipantSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkParticipantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkSpec) DeepCopyInto(out *StacksNetworkSpec) {
	*out = *in
	if in.EpochScheduleRef != nil {
		in, out := &in.EpochScheduleRef, &out.EpochScheduleRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.EpochSchedule != nil {
		in, out := &in.EpochSchedule, &out.EpochSchedule
		*out = new(StacksEpochScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(GenesisInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(Defaults)
		(*in).DeepCopyInto(*out)
	}
	if in.Participants != nil {
		in, out := &in.Participants, &out.Participants
		*out = make([]Participant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpectedInputDigest != nil {
		in, out := &in.ExpectedInputDigest, &out.ExpectedInputDigest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkSpec.
func (in *StacksNetworkSpec) DeepCopy() *StacksNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkStatus) DeepCopyInto(out *StacksNetworkStatus) {
	*out = *in
	if in.BurnchainObservations != nil {
		in, out := &in.BurnchainObservations, &out.BurnchainObservations
		*out = new(BurnchainObservations)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservationPolicy != nil {
		in, out := &in.ObservationPolicy, &out.ObservationPolicy
		*out = new(ObservationPolicy)
		**out = **in
	}
	if in.GenesisRef != nil {
		in, out := &in.GenesisRef, &out.GenesisRef
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.Identities != nil {
		in, out := &in.Identities, &out.Identities
		*out = make([]InstanceIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bitcoin != nil {
		in, out := &in.Bitcoin, &out.Bitcoin
		*out = new(BitcoinRuntimeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(InitializationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkStatus.
func (in *StacksNetworkStatus) DeepCopy() *StacksNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksProtocolObservation) DeepCopyInto(out *StacksProtocolObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	in.LastHeightAdvancedAt.DeepCopyInto(&out.LastHeightAdvancedAt)
	if in.PreparedSet != nil {
		in, out := &in.PreparedSet, &out.PreparedSet
		*out = new(PreparedSignerSetObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksProtocolObservation.
func (in *StacksProtocolObservation) DeepCopy() *StacksProtocolObservation {
	if in == nil {
		return nil
	}
	out := new(StacksProtocolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficObservation) DeepCopyInto(out *TrafficObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficObservation.
func (in *TrafficObservation) DeepCopy() *TrafficObservation {
	if in == nil {
		return nil
	}
	out := new(TrafficObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransactionExecutionStatus) DeepCopyInto(out *TransactionExecutionStatus) {
	*out = *in
	if in.LastPostcondition != nil {
		in, out := &in.LastPostcondition, &out.LastPostcondition
		*out = new(TransactionPostcondition)
		(*in).DeepCopyInto(*out)
	}
	if in.LastInclusion != nil {
		in, out := &in.LastInclusion, &out.LastInclusion
		*out = new(TransactionInclusion)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransactionExecutionStatus.
func (in *TransactionExecutionStatus) DeepCopy() *TransactionExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(TransactionExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransactionInclusion) DeepCopyInto(out *TransactionInclusion) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransactionInclusion.
func (in *TransactionInclusion) DeepCopy() *TransactionInclusion {
	if in == nil {
		return nil
	}
	out := new(TransactionInclusion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransactionPostcondition) DeepCopyInto(out *TransactionPostcondition) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransactionPostcondition.
func (in *TransactionPostcondition) DeepCopy() *TransactionPostcondition {
	if in == nil {
		return nil
	}
	out := new(TransactionPostcondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerCandidate) DeepCopyInto(out *WorkerCandidate) {
	*out = *in
	out.Pod = in.Pod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerCandidate.
func (in *WorkerCandidate) DeepCopy() *WorkerCandidate {
	if in == nil {
		return nil
	}
	out := new(WorkerCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerDisposal) DeepCopyInto(out *WorkerDisposal) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerDisposal.
func (in *WorkerDisposal) DeepCopy() *WorkerDisposal {
	if in == nil {
		return nil
	}
	out := new(WorkerDisposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerExecutionStatus) DeepCopyInto(out *WorkerExecutionStatus) {
	*out = *in
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(TrafficObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(stacksv1alpha2.FaucetWorkerSummary)
		(*in).DeepCopyInto(*out)
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Transactions != nil {
		in, out := &in.Transactions, &out.Transactions
		*out = new(TransactionExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PoX4 != nil {
		in, out := &in.PoX4, &out.PoX4
		*out = new(PoX4EnrollmentObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.PoX5 != nil {
		in, out := &in.PoX5, &out.PoX5
		*out = new(PoX5EnrollmentObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.AdministratorTransactions != nil {
		in, out := &in.AdministratorTransactions, &out.AdministratorTransactions
		*out = new(TransactionExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Contracts != nil {
		in, out := &in.Contracts, &out.Contracts
		*out = new(ContractSetObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerExecutionStatus.
func (in *WorkerExecutionStatus) DeepCopy() *WorkerExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPodBinding) DeepCopyInto(out *WorkerPodBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPodBinding.
func (in *WorkerPodBinding) DeepCopy() *WorkerPodBinding {
	if in == nil {
		return nil
	}
	out := new(WorkerPodBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSession) DeepCopyInto(out *WorkerSession) {
	*out = *in
	out.Pod = in.Pod
	if in.Shutdown != nil {
		in, out := &in.Shutdown, &out.Shutdown
		*out = new(WorkerShutdown)
		(*in).DeepCopyInto(*out)
	}
	if in.Disposal != nil {
		in, out := &in.Disposal, &out.Disposal
		*out = new(WorkerDisposal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSession.
func (in *WorkerSession) DeepCopy() *WorkerSession {
	if in == nil {
		return nil
	}
	out := new(WorkerSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerShutdown) DeepCopyInto(out *WorkerShutdown) {
	*out = *in
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerShutdown.
func (in *WorkerShutdown) DeepCopy() *WorkerShutdown {
	if in == nil {
		return nil
	}
	out := new(WorkerShutdown)
	in.DeepCopyInto(out)
	return out
}
