package telemetry

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	observation "github.com/cylewitruk-stacks/stacks-k8s/operators/observability/api/v1alpha2"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/yaml"
)

func TestSourceSelectionAndCollectorComponentGraph(t *testing.T) {
	for mask := 1; mask < 8; mask++ {
		t.Run(fmt.Sprint(mask), func(t *testing.T) {
			object := fixture()
			object.Spec.Sources = observation.Sources{Objects: mask&1 != 0, Logs: mask&2 != 0, Metrics: mask&4 != 0}
			config, err := CollectorConfig(object)
			if err != nil {
				t.Fatal(err)
			}
			var doc map[string]any
			if err := yaml.UnmarshalStrict([]byte(config), &doc); err != nil {
				t.Fatal(err)
			}
			service := doc["service"].(map[string]any)
			for _, name := range service["extensions"].([]any) {
				if doc["extensions"].(map[string]any)[name.(string)] == nil {
					t.Fatalf("undefined extension %s", name)
				}
			}
			for _, pipeline := range service["pipelines"].(map[string]any) {
				for _, section := range []string{"receivers", "processors", "exporters"} {
					for _, name := range pipeline.(map[string]any)[section].([]any) {
						if doc[section].(map[string]any)[name.(string)] == nil {
							t.Fatalf("undefined %s %s", section, name)
						}
					}
				}
			}
			objects, err := Resources(object, "recorder:test", DefaultCollectorImage)
			if err != nil {
				t.Fatal(err)
			}
			count := 0
			for _, resource := range objects {
				if ds, ok := resource.(*appsv1.DaemonSet); ok {
					count++
					for _, volume := range ds.Spec.Template.Spec.Volumes {
						if !object.Spec.Sources.Logs && volume.HostPath != nil {
							t.Fatal("metrics-only collector mounts host")
						}
					}
					if !object.Spec.Sources.Logs && *ds.Spec.Template.Spec.SecurityContext.RunAsUser == 0 {
						t.Fatal("metrics-only collector runs as root")
					}
				}
				if _, ok := resource.(*corev1.ConfigMap); ok && !NeedsCollector(object) {
					t.Fatal("objects-only collector configuration provisioned")
				}
			}
			if (count == 1) != NeedsCollector(object) {
				t.Fatalf("unexpected collectors %d", count)
			}
		})
	}
}

func TestRenderedRedactionAndIndexContracts(t *testing.T) {
	config, err := CollectorConfig(fixture())
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := yaml.UnmarshalStrict([]byte(config), &doc); err != nil {
		t.Fatal(err)
	}
	processors := doc["processors"].(map[string]any)
	logStatements := processors["transform/redaction"].(map[string]any)["log_statements"].([]any)
	statements := logStatements[0].(map[string]any)["statements"].([]any)
	statement := statements[len(statements)-1].(string)
	args := strings.TrimSuffix(strings.TrimPrefix(statement, "replace_pattern(body, "), ")")
	var decoded []string
	if err := json.Unmarshal([]byte("["+args+"]"), &decoded); err != nil {
		t.Fatal(err)
	}
	assignment := regexp.MustCompile(decoded[0])
	receivers := doc["receivers"].(map[string]any)
	jobs := receivers["prometheus"].(map[string]any)["config"].(map[string]any)["scrape_configs"].([]any)
	names := regexp.MustCompile(
		jobs[1].(map[string]any)["metric_relabel_configs"].([]any)[0].(map[string]any)["regex"].(string),
	)
	for _, name := range []string{
		"password", "privatekey", "private_key", "private-key", "authorization",
		"authtoken", "auth_token", "auth-token", "seed", "AUTH-TOKEN",
	} {
		if !names.MatchString(name) || assignment.ReplaceAllString(name+`="PRIVATE"`, "[REDACTED]") != "[REDACTED]" {
			t.Fatalf("rendered policy missed %s", name)
		}
	}
	headers := doc["exporters"].(map[string]any)["otlp_http/logs"].(map[string]any)["headers"].(map[string]any)
	if headers["X-Greptime-Log-Extract-Keys"] != "network_uid,participant_uid,pod_uid,object_uid,event_type,source" {
		t.Fatal("index contract diverged")
	}
}

func TestPinnedCollectorValidation(t *testing.T) {
	if os.Getenv("STACKS_TELEMETRY_COLLECTOR_VALIDATE") != "1" {
		t.Skip("enabled by make docker-check")
	}
	for mask := 1; mask < 8; mask++ {
		object := fixture()
		object.Spec.Sources = observation.Sources{Objects: mask&1 != 0, Logs: mask&2 != 0, Metrics: mask&4 != 0}
		config, err := CollectorConfig(object)
		if err != nil {
			t.Fatal(err)
		}
		path := filepath.Join(t.TempDir(), "collector.yaml")
		if err := os.WriteFile(path, []byte(config), 0o600); err != nil {
			t.Fatal(err)
		}
		// #nosec G204 -- Fixed Docker executable/image; mount path is generated by this test, never a user argument.
		cmd := exec.CommandContext(
			t.Context(),
			"docker",
			"run",
			"--rm",
			"--tmpfs", "/var/lib/otelcol:rw,mode=1777",
			"-v",
			path+":/config.yaml:ro",
			"-e",
			"GREPTIME_ENDPOINT=http://localhost:4000",
			"-e",
			"GREPTIME_AUTH=Basic_test",
			"-e",
			"NODE_NAME=test",
			"-e",
			"POD_UID=test",
			DefaultCollectorImage,
			"validate",
			"--config=/config.yaml",
		)
		if output, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("sources %d: %v\n%s", mask, err, output)
		}
	}
}
