//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProduction) DeepCopyInto(out *StacksTransactionProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProduction.
func (in *StacksTransactionProduction) DeepCopy() *StacksTransactionProduction {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksTransactionProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionList) DeepCopyInto(out *StacksTransactionProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksTransactionProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionList.
func (in *StacksTransactionProductionList) DeepCopy() *StacksTransactionProductionList {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksTransactionProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionSpec) DeepCopyInto(out *StacksTransactionProductionSpec) {
	*out = *in
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionSpec.
func (in *StacksTransactionProductionSpec) DeepCopy() *StacksTransactionProductionSpec {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionStatus) DeepCopyInto(out *StacksTransactionProductionStatus) {
	*out = *in
	if in.NextNonce != nil {
		in, out := &in.NextNonce, &out.NextNonce
		*out = new(int64)
		**out = **in
	}
	if in.SubmittedAt != nil {
		in, out := &in.SubmittedAt, &out.SubmittedAt
		*out = (*in).DeepCopy()
	}
	if in.LastConfirmedAt != nil {
		in, out := &in.LastConfirmedAt, &out.LastConfirmedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionStatus.
func (in *StacksTransactionProductionStatus) DeepCopy() *StacksTransactionProductionStatus {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferPolicy) DeepCopyInto(out *TransferPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferPolicy.
func (in *TransferPolicy) DeepCopy() *TransferPolicy {
	if in == nil {
		return nil
	}
	out := new(TransferPolicy)
	in.DeepCopyInto(out)
	return out
}
