//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountReceipt) DeepCopyInto(out *AccountReceipt) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountReceipt.
func (in *AccountReceipt) DeepCopy() *AccountReceipt {
	if in == nil {
		return nil
	}
	out := new(AccountReceipt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountTransaction) DeepCopyInto(out *AccountTransaction) {
	*out = *in
	in.AuthorizedAt.DeepCopyInto(&out.AuthorizedAt)
	if in.Receipt != nil {
		in, out := &in.Receipt, &out.Receipt
		*out = new(AccountReceipt)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountTransaction.
func (in *AccountTransaction) DeepCopy() *AccountTransaction {
	if in == nil {
		return nil
	}
	out := new(AccountTransaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactReference) DeepCopyInto(out *ArtifactReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactReference.
func (in *ArtifactReference) DeepCopy() *ArtifactReference {
	if in == nil {
		return nil
	}
	out := new(ArtifactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeInitialization) DeepCopyInto(out *BridgeInitialization) {
	*out = *in
	if in.SignerPublicKeys != nil {
		in, out := &in.SignerPublicKeys, &out.SignerPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeInitialization.
func (in *BridgeInitialization) DeepCopy() *BridgeInitialization {
	if in == nil {
		return nil
	}
	out := new(BridgeInitialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractArtifact) DeepCopyInto(out *ContractArtifact) {
	*out = *in
	out.SourceRef = in.SourceRef
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractArtifact.
func (in *ContractArtifact) DeepCopy() *ContractArtifact {
	if in == nil {
		return nil
	}
	out := new(ContractArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSetPolicy) DeepCopyInto(out *ContractSetPolicy) {
	*out = *in
	if in.Contracts != nil {
		in, out := &in.Contracts, &out.Contracts
		*out = make([]ContractArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bridge != nil {
		in, out := &in.Bridge, &out.Bridge
		*out = new(BridgeInitialization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSetPolicy.
func (in *ContractSetPolicy) DeepCopy() *ContractSetPolicy {
	if in == nil {
		return nil
	}
	out := new(ContractSetPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedAccountPolicy) DeepCopyInto(out *ManagedAccountPolicy) {
	*out = *in
	out.KeySecretRef = in.KeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedAccountPolicy.
func (in *ManagedAccountPolicy) DeepCopy() *ManagedAccountPolicy {
	if in == nil {
		return nil
	}
	out := new(ManagedAccountPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedOperationStatus) DeepCopyInto(out *ManagedOperationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Receipts != nil {
		in, out := &in.Receipts, &out.Receipts
		*out = make([]OperationAcknowledgement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedOperationStatus.
func (in *ManagedOperationStatus) DeepCopy() *ManagedOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationAcknowledgement) DeepCopyInto(out *OperationAcknowledgement) {
	*out = *in
	in.Transaction.DeepCopyInto(&out.Transaction)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationAcknowledgement.
func (in *OperationAcknowledgement) DeepCopy() *OperationAcknowledgement {
	if in == nil {
		return nil
	}
	out := new(OperationAcknowledgement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackingPolicy) DeepCopyInto(out *StackingPolicy) {
	*out = *in
	out.ConsensusKeySecretRef = in.ConsensusKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackingPolicy.
func (in *StackingPolicy) DeepCopy() *StackingPolicy {
	if in == nil {
		return nil
	}
	out := new(StackingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccount) DeepCopyInto(out *StacksAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccount.
func (in *StacksAccount) DeepCopy() *StacksAccount {
	if in == nil {
		return nil
	}
	out := new(StacksAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccountList) DeepCopyInto(out *StacksAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccountList.
func (in *StacksAccountList) DeepCopy() *StacksAccountList {
	if in == nil {
		return nil
	}
	out := new(StacksAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccountSpec) DeepCopyInto(out *StacksAccountSpec) {
	*out = *in
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccountSpec.
func (in *StacksAccountSpec) DeepCopy() *StacksAccountSpec {
	if in == nil {
		return nil
	}
	out := new(StacksAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccountStatus) DeepCopyInto(out *StacksAccountStatus) {
	*out = *in
	if in.Transaction != nil {
		in, out := &in.Transaction, &out.Transaction
		*out = new(AccountTransaction)
		(*in).DeepCopyInto(*out)
	}
	if in.NextNonce != nil {
		in, out := &in.NextNonce, &out.NextNonce
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccountStatus.
func (in *StacksAccountStatus) DeepCopy() *StacksAccountStatus {
	if in == nil {
		return nil
	}
	out := new(StacksAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksContractSet) DeepCopyInto(out *StacksContractSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksContractSet.
func (in *StacksContractSet) DeepCopy() *StacksContractSet {
	if in == nil {
		return nil
	}
	out := new(StacksContractSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksContractSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksContractSetList) DeepCopyInto(out *StacksContractSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksContractSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksContractSetList.
func (in *StacksContractSetList) DeepCopy() *StacksContractSetList {
	if in == nil {
		return nil
	}
	out := new(StacksContractSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksContractSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksContractSetSpec) DeepCopyInto(out *StacksContractSetSpec) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksContractSetSpec.
func (in *StacksContractSetSpec) DeepCopy() *StacksContractSetSpec {
	if in == nil {
		return nil
	}
	out := new(StacksContractSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksStackingParticipant) DeepCopyInto(out *StacksStackingParticipant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksStackingParticipant.
func (in *StacksStackingParticipant) DeepCopy() *StacksStackingParticipant {
	if in == nil {
		return nil
	}
	out := new(StacksStackingParticipant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksStackingParticipant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksStackingParticipantList) DeepCopyInto(out *StacksStackingParticipantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksStackingParticipant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksStackingParticipantList.
func (in *StacksStackingParticipantList) DeepCopy() *StacksStackingParticipantList {
	if in == nil {
		return nil
	}
	out := new(StacksStackingParticipantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksStackingParticipantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksStackingParticipantSpec) DeepCopyInto(out *StacksStackingParticipantSpec) {
	*out = *in
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksStackingParticipantSpec.
func (in *StacksStackingParticipantSpec) DeepCopy() *StacksStackingParticipantSpec {
	if in == nil {
		return nil
	}
	out := new(StacksStackingParticipantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProduction) DeepCopyInto(out *StacksTransactionProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProduction.
func (in *StacksTransactionProduction) DeepCopy() *StacksTransactionProduction {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksTransactionProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionList) DeepCopyInto(out *StacksTransactionProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksTransactionProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionList.
func (in *StacksTransactionProductionList) DeepCopy() *StacksTransactionProductionList {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksTransactionProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionSpec) DeepCopyInto(out *StacksTransactionProductionSpec) {
	*out = *in
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionSpec.
func (in *StacksTransactionProductionSpec) DeepCopy() *StacksTransactionProductionSpec {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionStatus) DeepCopyInto(out *StacksTransactionProductionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NextNonce != nil {
		in, out := &in.NextNonce, &out.NextNonce
		*out = new(int64)
		**out = **in
	}
	if in.SubmittedAt != nil {
		in, out := &in.SubmittedAt, &out.SubmittedAt
		*out = (*in).DeepCopy()
	}
	if in.LastConfirmedAt != nil {
		in, out := &in.LastConfirmedAt, &out.LastConfirmedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionStatus.
func (in *StacksTransactionProductionStatus) DeepCopy() *StacksTransactionProductionStatus {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferPolicy) DeepCopyInto(out *TransferPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferPolicy.
func (in *TransferPolicy) DeepCopy() *TransferPolicy {
	if in == nil {
		return nil
	}
	out := new(TransferPolicy)
	in.DeepCopyInto(out)
	return out
}
