//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	bitcoinv1alpha1 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/bitcoin/v1alpha1"
	stacksv1alpha1 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/stacks/v1alpha1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorIdentity) DeepCopyInto(out *ActorIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorIdentity.
func (in *ActorIdentity) DeepCopy() *ActorIdentity {
	if in == nil {
		return nil
	}
	out := new(ActorIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActorStatus) DeepCopyInto(out *ActorStatus) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(ActorIdentity)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActorStatus.
func (in *ActorStatus) DeepCopy() *ActorStatus {
	if in == nil {
		return nil
	}
	out := new(ActorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNode) DeepCopyInto(out *BitcoinNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNode.
func (in *BitcoinNode) DeepCopy() *BitcoinNode {
	if in == nil {
		return nil
	}
	out := new(BitcoinNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeList) DeepCopyInto(out *BitcoinNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeList.
func (in *BitcoinNodeList) DeepCopy() *BitcoinNodeList {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeSpec) DeepCopyInto(out *BitcoinNodeSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Config.DeepCopyInto(&out.Config)
	if in.PeerRefs != nil {
		in, out := &in.PeerRefs, &out.PeerRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Workload.DeepCopyInto(&out.Workload)
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeSpec.
func (in *BitcoinNodeSpec) DeepCopy() *BitcoinNodeSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinNodeTemplate) DeepCopyInto(out *BitcoinNodeTemplate) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.PeerRefs != nil {
		in, out := &in.PeerRefs, &out.PeerRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinNodeTemplate.
func (in *BitcoinNodeTemplate) DeepCopy() *BitcoinNodeTemplate {
	if in == nil {
		return nil
	}
	out := new(BitcoinNodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityIdentity) DeepCopyInto(out *CapabilityIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityIdentity.
func (in *CapabilityIdentity) DeepCopy() *CapabilityIdentity {
	if in == nil {
		return nil
	}
	out := new(CapabilityIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildStatus) DeepCopyInto(out *ChildStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildStatus.
func (in *ChildStatus) DeepCopy() *ChildStatus {
	if in == nil {
		return nil
	}
	out := new(ChildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObjectRef) DeepCopyInto(out *ConfigObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObjectRef.
func (in *ConfigObjectRef) DeepCopy() *ConfigObjectRef {
	if in == nil {
		return nil
	}
	out := new(ConfigObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = new(GeneratedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(InlineConfig)
		**out = **in
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigObjectRef)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(ConfigObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSource.
func (in *ConfigSource) DeepCopy() *ConfigSource {
	if in == nil {
		return nil
	}
	out := new(ConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerOverride) DeepCopyInto(out *ContainerOverride) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerOverride.
func (in *ContainerOverride) DeepCopy() *ContainerOverride {
	if in == nil {
		return nil
	}
	out := new(ContainerOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedConfig) DeepCopyInto(out *GeneratedConfig) {
	*out = *in
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedConfig.
func (in *GeneratedConfig) DeepCopy() *GeneratedConfig {
	if in == nil {
		return nil
	}
	out := new(GeneratedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisBalance) DeepCopyInto(out *GenesisBalance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisBalance.
func (in *GenesisBalance) DeepCopy() *GenesisBalance {
	if in == nil {
		return nil
	}
	out := new(GenesisBalance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisEpoch) DeepCopyInto(out *GenesisEpoch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisEpoch.
func (in *GenesisEpoch) DeepCopy() *GenesisEpoch {
	if in == nil {
		return nil
	}
	out := new(GenesisEpoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisPoX) DeepCopyInto(out *GenesisPoX) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisPoX.
func (in *GenesisPoX) DeepCopy() *GenesisPoX {
	if in == nil {
		return nil
	}
	out := new(GenesisPoX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisPoX5) DeepCopyInto(out *GenesisPoX5) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisPoX5.
func (in *GenesisPoX5) DeepCopy() *GenesisPoX5 {
	if in == nil {
		return nil
	}
	out := new(GenesisPoX5)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisSpec) DeepCopyInto(out *GenesisSpec) {
	*out = *in
	if in.UseTestGenesisChainstate != nil {
		in, out := &in.UseTestGenesisChainstate, &out.UseTestGenesisChainstate
		*out = new(bool)
		**out = **in
	}
	if in.Balances != nil {
		in, out := &in.Balances, &out.Balances
		*out = make([]GenesisBalance, len(*in))
		copy(*out, *in)
	}
	if in.Epochs != nil {
		in, out := &in.Epochs, &out.Epochs
		*out = make([]GenesisEpoch, len(*in))
		copy(*out, *in)
	}
	if in.PoX5 != nil {
		in, out := &in.PoX5, &out.PoX5
		*out = new(GenesisPoX5)
		**out = **in
	}
	if in.PoX != nil {
		in, out := &in.PoX, &out.PoX
		*out = new(GenesisPoX)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisSpec.
func (in *GenesisSpec) DeepCopy() *GenesisSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineConfig) DeepCopyInto(out *InlineConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineConfig.
func (in *InlineConfig) DeepCopy() *InlineConfig {
	if in == nil {
		return nil
	}
	out := new(InlineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDefaults) DeepCopyInto(out *NetworkDefaults) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDefaults.
func (in *NetworkDefaults) DeepCopy() *NetworkDefaults {
	if in == nil {
		return nil
	}
	out := new(NetworkDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkOperation) DeepCopyInto(out *NetworkOperation) {
	*out = *in
	if in.Accounts != nil {
		in, out := &in.Accounts, &out.Accounts
		*out = make([]stacksv1alpha1.ManagedAccountPolicy, len(*in))
		copy(*out, *in)
	}
	if in.ContractSets != nil {
		in, out := &in.ContractSets, &out.ContractSets
		*out = make([]stacksv1alpha1.ContractSetPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Participants != nil {
		in, out := &in.Participants, &out.Participants
		*out = make([]stacksv1alpha1.StackingPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkOperation.
func (in *NetworkOperation) DeepCopy() *NetworkOperation {
	if in == nil {
		return nil
	}
	out := new(NetworkOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortSpec) DeepCopyInto(out *PortSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortSpec.
func (in *PortSpec) DeepCopy() *PortSpec {
	if in == nil {
		return nil
	}
	out := new(PortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceValues) DeepCopyInto(out *ResourceValues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceValues.
func (in *ResourceValues) DeepCopy() *ResourceValues {
	if in == nil {
		return nil
	}
	out := new(ResourceValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisProfile) DeepCopyInto(out *StacksGenesisProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisProfile.
func (in *StacksGenesisProfile) DeepCopy() *StacksGenesisProfile {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksGenesisProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksGenesisProfileList) DeepCopyInto(out *StacksGenesisProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksGenesisProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksGenesisProfileList.
func (in *StacksGenesisProfileList) DeepCopy() *StacksGenesisProfileList {
	if in == nil {
		return nil
	}
	out := new(StacksGenesisProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksGenesisProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetwork) DeepCopyInto(out *StacksNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetwork.
func (in *StacksNetwork) DeepCopy() *StacksNetwork {
	if in == nil {
		return nil
	}
	out := new(StacksNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkList) DeepCopyInto(out *StacksNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkList.
func (in *StacksNetworkList) DeepCopy() *StacksNetworkList {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkSpec) DeepCopyInto(out *StacksNetworkSpec) {
	*out = *in
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(NetworkOperation)
		(*in).DeepCopyInto(*out)
	}
	if in.StacksTransactionProduction != nil {
		in, out := &in.StacksTransactionProduction, &out.StacksTransactionProduction
		*out = new(stacksv1alpha1.TransferPolicy)
		**out = **in
	}
	if in.BitcoinBlockProduction != nil {
		in, out := &in.BitcoinBlockProduction, &out.BitcoinBlockProduction
		*out = new(bitcoinv1alpha1.ProductionPolicy)
		(*in).DeepCopyInto(*out)
	}
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(GenesisSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BitcoinNodes != nil {
		in, out := &in.BitcoinNodes, &out.BitcoinNodes
		*out = make([]BitcoinNodeTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StacksNodes != nil {
		in, out := &in.StacksNodes, &out.StacksNodes
		*out = make([]StacksNodeTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Signers != nil {
		in, out := &in.Signers, &out.Signers
		*out = make([]StacksSignerTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkSpec.
func (in *StacksNetworkSpec) DeepCopy() *StacksNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNetworkStatus) DeepCopyInto(out *StacksNetworkStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]CapabilityIdentity, len(*in))
		copy(*out, *in)
	}
	if in.TargetDeclarations != nil {
		in, out := &in.TargetDeclarations, &out.TargetDeclarations
		*out = new(TargetDeclarations)
		(*in).DeepCopyInto(*out)
	}
	if in.InventoryObservedAt != nil {
		in, out := &in.InventoryObservedAt, &out.InventoryObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]ActorIdentity, len(*in))
		copy(*out, *in)
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ChildStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNetworkStatus.
func (in *StacksNetworkStatus) DeepCopy() *StacksNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(StacksNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNode) DeepCopyInto(out *StacksNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNode.
func (in *StacksNode) DeepCopy() *StacksNode {
	if in == nil {
		return nil
	}
	out := new(StacksNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNodeList) DeepCopyInto(out *StacksNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNodeList.
func (in *StacksNodeList) DeepCopy() *StacksNodeList {
	if in == nil {
		return nil
	}
	out := new(StacksNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNodeSpec) DeepCopyInto(out *StacksNodeSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	out.BitcoinNodeRef = in.BitcoinNodeRef
	if in.SignerRef != nil {
		in, out := &in.SignerRef, &out.SignerRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.SignerIndex != nil {
		in, out := &in.SignerIndex, &out.SignerIndex
		*out = new(int32)
		**out = **in
	}
	in.Config.DeepCopyInto(&out.Config)
	if in.ServiceMap != nil {
		in, out := &in.ServiceMap, &out.ServiceMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BootstrapPeers != nil {
		in, out := &in.BootstrapPeers, &out.BootstrapPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(GenesisSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Workload.DeepCopyInto(&out.Workload)
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNodeSpec.
func (in *StacksNodeSpec) DeepCopy() *StacksNodeSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNodeTemplate) DeepCopyInto(out *StacksNodeTemplate) {
	*out = *in
	if in.ServiceRefs != nil {
		in, out := &in.ServiceRefs, &out.ServiceRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Config.DeepCopyInto(&out.Config)
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNodeTemplate.
func (in *StacksNodeTemplate) DeepCopy() *StacksNodeTemplate {
	if in == nil {
		return nil
	}
	out := new(StacksNodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSigner) DeepCopyInto(out *StacksSigner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSigner.
func (in *StacksSigner) DeepCopy() *StacksSigner {
	if in == nil {
		return nil
	}
	out := new(StacksSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksSigner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSignerList) DeepCopyInto(out *StacksSignerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksSigner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSignerList.
func (in *StacksSignerList) DeepCopy() *StacksSignerList {
	if in == nil {
		return nil
	}
	out := new(StacksSignerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksSignerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSignerSpec) DeepCopyInto(out *StacksSignerSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	out.NodeRef = in.NodeRef
	in.Config.DeepCopyInto(&out.Config)
	if in.ServiceMap != nil {
		in, out := &in.ServiceMap, &out.ServiceMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Workload.DeepCopyInto(&out.Workload)
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSignerSpec.
func (in *StacksSignerSpec) DeepCopy() *StacksSignerSpec {
	if in == nil {
		return nil
	}
	out := new(StacksSignerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSignerTemplate) DeepCopyInto(out *StacksSignerTemplate) {
	*out = *in
	if in.ServiceRefs != nil {
		in, out := &in.ServiceRefs, &out.ServiceRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Config.DeepCopyInto(&out.Config)
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSignerTemplate.
func (in *StacksSignerTemplate) DeepCopy() *StacksSignerTemplate {
	if in == nil {
		return nil
	}
	out := new(StacksSignerTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDeclaration) DeepCopyInto(out *TargetDeclaration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDeclaration.
func (in *TargetDeclaration) DeepCopy() *TargetDeclaration {
	if in == nil {
		return nil
	}
	out := new(TargetDeclaration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDeclarations) DeepCopyInto(out *TargetDeclarations) {
	*out = *in
	if in.Actors != nil {
		in, out := &in.Actors, &out.Actors
		*out = make([]TargetDeclaration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDeclarations.
func (in *TargetDeclarations) DeepCopy() *TargetDeclarations {
	if in == nil {
		return nil
	}
	out := new(TargetDeclarations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TolerationSpec) DeepCopyInto(out *TolerationSpec) {
	*out = *in
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TolerationSpec.
func (in *TolerationSpec) DeepCopy() *TolerationSpec {
	if in == nil {
		return nil
	}
	out := new(TolerationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]TolerationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
