//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	commonv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/common/v1alpha2"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetAdmission) DeepCopyInto(out *FaucetAdmission) {
	*out = *in
	if in.Faucet != nil {
		in, out := &in.Faucet, &out.Faucet
		*out = new(FaucetBinding)
		**out = **in
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(FaucetBinding)
		**out = **in
	}
	if in.SourceAccount != nil {
		in, out := &in.SourceAccount, &out.SourceAccount
		*out = new(FaucetBinding)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(FaucetBinding)
		**out = **in
	}
	if in.DestinationAccount != nil {
		in, out := &in.DestinationAccount, &out.DestinationAccount
		*out = new(FaucetBinding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetAdmission.
func (in *FaucetAdmission) DeepCopy() *FaucetAdmission {
	if in == nil {
		return nil
	}
	out := new(FaucetAdmission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetBinding) DeepCopyInto(out *FaucetBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetBinding.
func (in *FaucetBinding) DeepCopy() *FaucetBinding {
	if in == nil {
		return nil
	}
	out := new(FaucetBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetExecution) DeepCopyInto(out *FaucetExecution) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetExecution.
func (in *FaucetExecution) DeepCopy() *FaucetExecution {
	if in == nil {
		return nil
	}
	out := new(FaucetExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetRequestStatus) DeepCopyInto(out *FaucetRequestStatus) {
	*out = *in
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(FaucetAdmission)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(FaucetExecution)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetRequestStatus.
func (in *FaucetRequestStatus) DeepCopy() *FaucetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(FaucetRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetRetainedOutcome) DeepCopyInto(out *FaucetRetainedOutcome) {
	*out = *in
	out.Request = in.Request
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetRetainedOutcome.
func (in *FaucetRetainedOutcome) DeepCopy() *FaucetRetainedOutcome {
	if in == nil {
		return nil
	}
	out := new(FaucetRetainedOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaucetWorkerSummary) DeepCopyInto(out *FaucetWorkerSummary) {
	*out = *in
	if in.LastDeletedOutcome != nil {
		in, out := &in.LastDeletedOutcome, &out.LastDeletedOutcome
		*out = new(FaucetRetainedOutcome)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaucetWorkerSummary.
func (in *FaucetWorkerSummary) DeepCopy() *FaucetWorkerSummary {
	if in == nil {
		return nil
	}
	out := new(FaucetWorkerSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mining) DeepCopyInto(out *Mining) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BitcoinWalletRef != nil {
		in, out := &in.BitcoinWalletRef, &out.BitcoinWalletRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.FeeRateSatsPerVByte != nil {
		in, out := &in.FeeRateSatsPerVByte, &out.FeeRateSatsPerVByte
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mining.
func (in *Mining) DeepCopy() *Mining {
	if in == nil {
		return nil
	}
	out := new(Mining)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recipient) DeepCopyInto(out *Recipient) {
	*out = *in
	if in.AccountRef != nil {
		in, out := &in.AccountRef, &out.AccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recipient.
func (in *Recipient) DeepCopy() *Recipient {
	if in == nil {
		return nil
	}
	out := new(Recipient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryInitialization) DeepCopyInto(out *RegistryInitialization) {
	*out = *in
	if in.SignerAccountRefs != nil {
		in, out := &in.SignerAccountRefs, &out.SignerAccountRefs
		*out = make([]commonv1alpha2.NameRef, len(*in))
		copy(*out, *in)
	}
	out.AggregateKeyAccountRef = in.AggregateKeyAccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryInitialization.
func (in *RegistryInitialization) DeepCopy() *RegistryInitialization {
	if in == nil {
		return nil
	}
	out := new(RegistryInitialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccount) DeepCopyInto(out *StacksAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccount.
func (in *StacksAccount) DeepCopy() *StacksAccount {
	if in == nil {
		return nil
	}
	out := new(StacksAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccountList) DeepCopyInto(out *StacksAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccountList.
func (in *StacksAccountList) DeepCopy() *StacksAccountList {
	if in == nil {
		return nil
	}
	out := new(StacksAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksAccountSpec) DeepCopyInto(out *StacksAccountSpec) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(commonv1alpha2.KeySource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksAccountSpec.
func (in *StacksAccountSpec) DeepCopy() *StacksAccountSpec {
	if in == nil {
		return nil
	}
	out := new(StacksAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksContractSet) DeepCopyInto(out *StacksContractSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksContractSet.
func (in *StacksContractSet) DeepCopy() *StacksContractSet {
	if in == nil {
		return nil
	}
	out := new(StacksContractSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksContractSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksContractSetList) DeepCopyInto(out *StacksContractSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksContractSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksContractSetList.
func (in *StacksContractSetList) DeepCopy() *StacksContractSetList {
	if in == nil {
		return nil
	}
	out := new(StacksContractSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksContractSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksContractSetSpec) DeepCopyInto(out *StacksContractSetSpec) {
	*out = *in
	in.WorkerFields.DeepCopyInto(&out.WorkerFields)
	if in.DeployerAccountRef != nil {
		in, out := &in.DeployerAccountRef, &out.DeployerAccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.TargetNodeRef != nil {
		in, out := &in.TargetNodeRef, &out.TargetNodeRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Bundle != nil {
		in, out := &in.Bundle, &out.Bundle
		*out = new(string)
		**out = **in
	}
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(RegistryInitialization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksContractSetSpec.
func (in *StacksContractSetSpec) DeepCopy() *StacksContractSetSpec {
	if in == nil {
		return nil
	}
	out := new(StacksContractSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksFaucet) DeepCopyInto(out *StacksFaucet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksFaucet.
func (in *StacksFaucet) DeepCopy() *StacksFaucet {
	if in == nil {
		return nil
	}
	out := new(StacksFaucet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksFaucet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksFaucetList) DeepCopyInto(out *StacksFaucetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksFaucet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksFaucetList.
func (in *StacksFaucetList) DeepCopy() *StacksFaucetList {
	if in == nil {
		return nil
	}
	out := new(StacksFaucetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksFaucetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksFaucetRequest) DeepCopyInto(out *StacksFaucetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksFaucetRequest.
func (in *StacksFaucetRequest) DeepCopy() *StacksFaucetRequest {
	if in == nil {
		return nil
	}
	out := new(StacksFaucetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksFaucetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksFaucetRequestList) DeepCopyInto(out *StacksFaucetRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksFaucetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksFaucetRequestList.
func (in *StacksFaucetRequestList) DeepCopy() *StacksFaucetRequestList {
	if in == nil {
		return nil
	}
	out := new(StacksFaucetRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksFaucetRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksFaucetRequestSpec) DeepCopyInto(out *StacksFaucetRequestSpec) {
	*out = *in
	out.FaucetRef = in.FaucetRef
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksFaucetRequestSpec.
func (in *StacksFaucetRequestSpec) DeepCopy() *StacksFaucetRequestSpec {
	if in == nil {
		return nil
	}
	out := new(StacksFaucetRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksFaucetSpec) DeepCopyInto(out *StacksFaucetSpec) {
	*out = *in
	in.WorkerFields.DeepCopyInto(&out.WorkerFields)
	if in.AccountRef != nil {
		in, out := &in.AccountRef, &out.AccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.GenesisBalanceMicroSTX != nil {
		in, out := &in.GenesisBalanceMicroSTX, &out.GenesisBalanceMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
	if in.TargetNodeRef != nil {
		in, out := &in.TargetNodeRef, &out.TargetNodeRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.MaxRequestMicroSTX != nil {
		in, out := &in.MaxRequestMicroSTX, &out.MaxRequestMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksFaucetSpec.
func (in *StacksFaucetSpec) DeepCopy() *StacksFaucetSpec {
	if in == nil {
		return nil
	}
	out := new(StacksFaucetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNode) DeepCopyInto(out *StacksNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNode.
func (in *StacksNode) DeepCopy() *StacksNode {
	if in == nil {
		return nil
	}
	out := new(StacksNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNodeList) DeepCopyInto(out *StacksNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNodeList.
func (in *StacksNodeList) DeepCopy() *StacksNodeList {
	if in == nil {
		return nil
	}
	out := new(StacksNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksNodeSpec) DeepCopyInto(out *StacksNodeSpec) {
	*out = *in
	in.ActorFields.DeepCopyInto(&out.ActorFields)
	if in.BitcoinNodeRef != nil {
		in, out := &in.BitcoinNodeRef, &out.BitcoinNodeRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.IdentityAccountRef != nil {
		in, out := &in.IdentityAccountRef, &out.IdentityAccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Mining != nil {
		in, out := &in.Mining, &out.Mining
		*out = new(Mining)
		(*in).DeepCopyInto(*out)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = new(commonv1alpha2.Peers)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksNodeSpec.
func (in *StacksNodeSpec) DeepCopy() *StacksNodeSpec {
	if in == nil {
		return nil
	}
	out := new(StacksNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSigner) DeepCopyInto(out *StacksSigner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSigner.
func (in *StacksSigner) DeepCopy() *StacksSigner {
	if in == nil {
		return nil
	}
	out := new(StacksSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksSigner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSignerList) DeepCopyInto(out *StacksSignerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksSigner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSignerList.
func (in *StacksSignerList) DeepCopy() *StacksSignerList {
	if in == nil {
		return nil
	}
	out := new(StacksSignerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksSignerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksSignerSpec) DeepCopyInto(out *StacksSignerSpec) {
	*out = *in
	in.ActorFields.DeepCopyInto(&out.ActorFields)
	if in.NodeRef != nil {
		in, out := &in.NodeRef, &out.NodeRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.AccountRef != nil {
		in, out := &in.AccountRef, &out.AccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksSignerSpec.
func (in *StacksSignerSpec) DeepCopy() *StacksSignerSpec {
	if in == nil {
		return nil
	}
	out := new(StacksSignerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksStacker) DeepCopyInto(out *StacksStacker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksStacker.
func (in *StacksStacker) DeepCopy() *StacksStacker {
	if in == nil {
		return nil
	}
	out := new(StacksStacker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksStacker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksStackerList) DeepCopyInto(out *StacksStackerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksStacker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksStackerList.
func (in *StacksStackerList) DeepCopy() *StacksStackerList {
	if in == nil {
		return nil
	}
	out := new(StacksStackerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksStackerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksStackerSpec) DeepCopyInto(out *StacksStackerSpec) {
	*out = *in
	in.WorkerFields.DeepCopyInto(&out.WorkerFields)
	if in.HolderAccountRef != nil {
		in, out := &in.HolderAccountRef, &out.HolderAccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.AdministratorAccountRef != nil {
		in, out := &in.AdministratorAccountRef, &out.AdministratorAccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.SignerRef != nil {
		in, out := &in.SignerRef, &out.SignerRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.TargetNodeRef != nil {
		in, out := &in.TargetNodeRef, &out.TargetNodeRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.AmountMicroSTX != nil {
		in, out := &in.AmountMicroSTX, &out.AmountMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
	if in.LockCycles != nil {
		in, out := &in.LockCycles, &out.LockCycles
		*out = new(int32)
		**out = **in
	}
	if in.RenewWhenRemainingCycles != nil {
		in, out := &in.RenewWhenRemainingCycles, &out.RenewWhenRemainingCycles
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksStackerSpec.
func (in *StacksStackerSpec) DeepCopy() *StacksStackerSpec {
	if in == nil {
		return nil
	}
	out := new(StacksStackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProduction) DeepCopyInto(out *StacksTransactionProduction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProduction.
func (in *StacksTransactionProduction) DeepCopy() *StacksTransactionProduction {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProduction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksTransactionProduction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionList) DeepCopyInto(out *StacksTransactionProductionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StacksTransactionProduction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionList.
func (in *StacksTransactionProductionList) DeepCopy() *StacksTransactionProductionList {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StacksTransactionProductionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StacksTransactionProductionSpec) DeepCopyInto(out *StacksTransactionProductionSpec) {
	*out = *in
	in.WorkerFields.DeepCopyInto(&out.WorkerFields)
	if in.AccountRef != nil {
		in, out := &in.AccountRef, &out.AccountRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.TargetNodeRef != nil {
		in, out := &in.TargetNodeRef, &out.TargetNodeRef
		*out = new(commonv1alpha2.NameRef)
		**out = **in
	}
	if in.Recipient != nil {
		in, out := &in.Recipient, &out.Recipient
		*out = new(Recipient)
		(*in).DeepCopyInto(*out)
	}
	if in.AmountMicroSTX != nil {
		in, out := &in.AmountMicroSTX, &out.AmountMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
	if in.FeeMicroSTX != nil {
		in, out := &in.FeeMicroSTX, &out.FeeMicroSTX
		*out = new(commonv1alpha2.Amount)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(commonv1alpha2.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StacksTransactionProductionSpec.
func (in *StacksTransactionProductionSpec) DeepCopy() *StacksTransactionProductionSpec {
	if in == nil {
		return nil
	}
	out := new(StacksTransactionProductionSpec)
	in.DeepCopyInto(out)
	return out
}
