apiVersion: v2
name: stacks-network-operator
description: Composable regtest networks, actor workloads and ongoing Stacks protocol operation
type: application
version: 0.1.0
appVersion: 0.1.0
kubeVersion: '>=1.37.0-0'
