image:
  repository: ghcr.io/cylewitruk-stacks/stacks-action-operator
  tag: dev
  pullPolicy: IfNotPresent
bitcoinGeneration:
  enabled: true
bitcoinReorganization:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    memory: 128Mi
