{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stacks-observability-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stacks-observability-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
