apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "stacks-network-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stacks-network-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["stacks.stacks.org"]
    resources: ["stackstransactionproductions"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["bitcoin.stacks.org"]
    resources: ["bitcoinblockproductions"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["network.stacks.org"]
    resources: ["stacksnetworks"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["network.stacks.org"]
    resources: ["bitcoinnodes", "stacksnodes", "stackssigners"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["network.stacks.org"]
    resources: ["stacksnetworks/status", "bitcoinnodes/status", "stacksnodes/status", "stackssigners/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "stacks-network-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stacks-network-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stacks-network-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "stacks-network-operator.fullname" . }}
