//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	commonv1alpha2 "github.com/cylewitruk-stacks/stacks-k8s/apis/network/common/v1alpha2"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockGeneration) DeepCopyInto(out *BitcoinBlockGeneration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockGeneration.
func (in *BitcoinBlockGeneration) DeepCopy() *BitcoinBlockGeneration {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockGeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockGeneration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockGenerationList) DeepCopyInto(out *BitcoinBlockGenerationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinBlockGeneration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockGenerationList.
func (in *BitcoinBlockGenerationList) DeepCopy() *BitcoinBlockGenerationList {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockGenerationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinBlockGenerationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockGenerationSpec) DeepCopyInto(out *BitcoinBlockGenerationSpec) {
	*out = *in
	out.BitcoinNodeRef = in.BitcoinNodeRef
	in.Cadence.DeepCopyInto(&out.Cadence)
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockGenerationSpec.
func (in *BitcoinBlockGenerationSpec) DeepCopy() *BitcoinBlockGenerationSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockGenerationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinBlockGenerationStatus) DeepCopyInto(out *BitcoinBlockGenerationStatus) {
	*out = *in
	if in.AdmittedExecution != nil {
		in, out := &in.AdmittedExecution, &out.AdmittedExecution
		*out = new(commonv1alpha2.Binding)
		**out = **in
	}
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.AdmittedNetwork != nil {
		in, out := &in.AdmittedNetwork, &out.AdmittedNetwork
		*out = new(NetworkIdentity)
		**out = **in
	}
	if in.AdmittedTarget != nil {
		in, out := &in.AdmittedTarget, &out.AdmittedTarget
		*out = new(TargetIdentity)
		**out = **in
	}
	if in.AdmittedPolicy != nil {
		in, out := &in.AdmittedPolicy, &out.AdmittedPolicy
		*out = new(PolicyIdentity)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinBlockGenerationStatus.
func (in *BitcoinBlockGenerationStatus) DeepCopy() *BitcoinBlockGenerationStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinBlockGenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinChainPoint) DeepCopyInto(out *BitcoinChainPoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinChainPoint.
func (in *BitcoinChainPoint) DeepCopy() *BitcoinChainPoint {
	if in == nil {
		return nil
	}
	out := new(BitcoinChainPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinReorganization) DeepCopyInto(out *BitcoinReorganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinReorganization.
func (in *BitcoinReorganization) DeepCopy() *BitcoinReorganization {
	if in == nil {
		return nil
	}
	out := new(BitcoinReorganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinReorganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinReorganizationList) DeepCopyInto(out *BitcoinReorganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitcoinReorganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinReorganizationList.
func (in *BitcoinReorganizationList) DeepCopy() *BitcoinReorganizationList {
	if in == nil {
		return nil
	}
	out := new(BitcoinReorganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitcoinReorganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinReorganizationSpec) DeepCopyInto(out *BitcoinReorganizationSpec) {
	*out = *in
	out.BitcoinNodeRef = in.BitcoinNodeRef
	out.BoundaryPolicy = in.BoundaryPolicy
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinReorganizationSpec.
func (in *BitcoinReorganizationSpec) DeepCopy() *BitcoinReorganizationSpec {
	if in == nil {
		return nil
	}
	out := new(BitcoinReorganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitcoinReorganizationStatus) DeepCopyInto(out *BitcoinReorganizationStatus) {
	*out = *in
	in.BitcoinBlockGenerationStatus.DeepCopyInto(&out.BitcoinBlockGenerationStatus)
	if in.OriginalChain != nil {
		in, out := &in.OriginalChain, &out.OriginalChain
		*out = new(BitcoinChainPoint)
		**out = **in
	}
	if in.ForkParent != nil {
		in, out := &in.ForkParent, &out.ForkParent
		*out = new(BitcoinChainPoint)
		**out = **in
	}
	if in.ReplacementBlockHashes != nil {
		in, out := &in.ReplacementBlockHashes, &out.ReplacementBlockHashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FinalChain != nil {
		in, out := &in.FinalChain, &out.FinalChain
		*out = new(BitcoinChainPoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitcoinReorganizationStatus.
func (in *BitcoinReorganizationStatus) DeepCopy() *BitcoinReorganizationStatus {
	if in == nil {
		return nil
	}
	out := new(BitcoinReorganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerationCadence) DeepCopyInto(out *GenerationCadence) {
	*out = *in
	if in.DelaysSeconds != nil {
		in, out := &in.DelaysSeconds, &out.DelaysSeconds
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerationCadence.
func (in *GenerationCadence) DeepCopy() *GenerationCadence {
	if in == nil {
		return nil
	}
	out := new(GenerationCadence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalReference) DeepCopyInto(out *LocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalReference.
func (in *LocalReference) DeepCopy() *LocalReference {
	if in == nil {
		return nil
	}
	out := new(LocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkIdentity) DeepCopyInto(out *NetworkIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkIdentity.
func (in *NetworkIdentity) DeepCopy() *NetworkIdentity {
	if in == nil {
		return nil
	}
	out := new(NetworkIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIdentity) DeepCopyInto(out *PolicyIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIdentity.
func (in *PolicyIdentity) DeepCopy() *PolicyIdentity {
	if in == nil {
		return nil
	}
	out := new(PolicyIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReorganizationBoundaryPolicy) DeepCopyInto(out *ReorganizationBoundaryPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReorganizationBoundaryPolicy.
func (in *ReorganizationBoundaryPolicy) DeepCopy() *ReorganizationBoundaryPolicy {
	if in == nil {
		return nil
	}
	out := new(ReorganizationBoundaryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetIdentity) DeepCopyInto(out *TargetIdentity) {
	*out = *in
	out.Configuration = in.Configuration
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetIdentity.
func (in *TargetIdentity) DeepCopy() *TargetIdentity {
	if in == nil {
		return nil
	}
	out := new(TargetIdentity)
	in.DeepCopyInto(out)
	return out
}
